// This file was auto-generated by Fern from our API Definition.

export interface GetExperienceViewResponseExtensionsSourceMapAssetsItem {
    space: number;
    environment: number;
    id: string;
}
