// This file was auto-generated by Fern from our API Definition.

export interface GetExperienceViewResponseExtensionsPersonalizationProfileLocationCoordinates {
    latitude: number;
    longitude: number;
}
