// This file was auto-generated by Fern from our API Definition.

export interface GetExperienceWithOverridesViewResponseSysEnvironmentSys {
    type: "Link";
    linkType: "Environment";
    id: string;
}
