// This file was auto-generated by Fern from our API Definition.

export interface GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContextLibrary {
    name: string;
    version: string;
}
