// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export interface GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContext {
    app?: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContextApp;
    campaign?: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContextCampaign;
    library: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContextLibrary;
    locale?: string;
    location?: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContextLocation;
    page?: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContextPage;
    userAgent?: string;
}
