// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export type GetExperienceViewResponseExtensionsSourceMapLayersItem =
    | ContentfulViewDelivery.GetExperienceViewResponseExtensionsSourceMapLayersItem.ComponentType
    | ContentfulViewDelivery.GetExperienceViewResponseExtensionsSourceMapLayersItem.Template
    | ContentfulViewDelivery.GetExperienceViewResponseExtensionsSourceMapLayersItem.Slot
    | ContentfulViewDelivery.GetExperienceViewResponseExtensionsSourceMapLayersItem.Experience
    | ContentfulViewDelivery.GetExperienceViewResponseExtensionsSourceMapLayersItem.Fragment
    | ContentfulViewDelivery.GetExperienceViewResponseExtensionsSourceMapLayersItem.InlineFragment;

export namespace GetExperienceViewResponseExtensionsSourceMapLayersItem {
    export interface ComponentType
        extends ContentfulViewDelivery.GetExperienceViewResponseExtensionsSourceMapLayersItemComponentType {
        kind: "ComponentType";
    }

    export interface Template
        extends ContentfulViewDelivery.GetExperienceViewResponseExtensionsSourceMapLayersItemTemplate {
        kind: "Template";
    }

    export interface Slot extends ContentfulViewDelivery.GetExperienceViewResponseExtensionsSourceMapLayersItemSlot {
        kind: "Slot";
    }

    export interface Experience
        extends ContentfulViewDelivery.GetExperienceViewResponseExtensionsSourceMapLayersItemExperience {
        kind: "Experience";
    }

    export interface Fragment
        extends ContentfulViewDelivery.GetExperienceViewResponseExtensionsSourceMapLayersItemFragment {
        kind: "Fragment";
    }

    export interface InlineFragment
        extends ContentfulViewDelivery.GetExperienceViewResponseExtensionsSourceMapLayersItemInlineFragment {
        kind: "InlineFragment";
    }
}
