// This file was auto-generated by Fern from our API Definition.

export const GetExperienceWithOverridesViewRequestPreview = {
    True: "true",
    False: "false",
} as const;
export type GetExperienceWithOverridesViewRequestPreview =
    (typeof GetExperienceWithOverridesViewRequestPreview)[keyof typeof GetExperienceWithOverridesViewRequestPreview];
