// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export interface GetExperienceViewResponseSysArchivedBy {
    sys: ContentfulViewDelivery.GetExperienceViewResponseSysArchivedBySys;
}
