// This file was auto-generated by Fern from our API Definition.

export const GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentComponentType = {
    Entry: "Entry",
    Variable: "Variable",
} as const;
export type GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentComponentType =
    (typeof GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentComponentType)[keyof typeof GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentComponentType];
