// This file was auto-generated by Fern from our API Definition.

export interface GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentifyContextApp {
    name: string;
    version: string;
}
