// This file was auto-generated by Fern from our API Definition.

export const GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackChannel = {
    Web: "web",
    Mobile: "mobile",
    Server: "server",
    Client: "client",
} as const;
export type GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackChannel =
    (typeof GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackChannel)[keyof typeof GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackChannel];
