// This file was auto-generated by Fern from our API Definition.

export interface GetExperienceWithOverridesViewResponseExtensionsSourceMapAssetsItem {
    space: number;
    environment: number;
    id: string;
}
