// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export interface GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrack {
    channel: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackChannel;
    context: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContext;
    messageId: string;
    timestamp: string;
    originalTimestamp?: string;
    sentAt?: string;
    userId?: string;
    event: string;
    properties?: Record<string, unknown>;
}
