// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export type GetExperienceWithOverridesViewResponseExtensionsPersonalizationChangesItem =
    | ContentfulViewDelivery.GetExperienceWithOverridesViewResponseExtensionsPersonalizationChangesItem.Experience
    | ContentfulViewDelivery.GetExperienceWithOverridesViewResponseExtensionsPersonalizationChangesItem.Fragment;

export namespace GetExperienceWithOverridesViewResponseExtensionsPersonalizationChangesItem {
    export interface Experience
        extends ContentfulViewDelivery.GetExperienceWithOverridesViewResponseExtensionsPersonalizationChangesItemExperience {
        type: "Experience";
    }

    export interface Fragment
        extends ContentfulViewDelivery.GetExperienceWithOverridesViewResponseExtensionsPersonalizationChangesItemFragment {
        type: "Fragment";
    }
}
