// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export interface GetExperienceViewResponseExtensionsPersonalizationProfileSession {
    id?: string;
    isReturningVisitor: boolean;
    landingPage: ContentfulViewDelivery.GetExperienceViewResponseExtensionsPersonalizationProfileSessionLandingPage;
    count: number;
    activeSessionLength: number;
    averageSessionLength: number;
}
