// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export interface GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreen {
    channel: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenChannel;
    context: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenContext;
    messageId: string;
    timestamp: string;
    originalTimestamp?: string;
    sentAt?: string;
    userId?: string;
    properties: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenProperties;
}
