// This file was auto-generated by Fern from our API Definition.

export const GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentifyChannel = {
    Web: "web",
    Mobile: "mobile",
    Server: "server",
    Client: "client",
} as const;
export type GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentifyChannel =
    (typeof GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentifyChannel)[keyof typeof GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentifyChannel];
