// This file was auto-generated by Fern from our API Definition.

export interface GetExperienceWithOverridesViewResponseViewportsItem {
    id: string;
    query: string;
    displayName: string;
    previewSize: string;
}
