// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export interface GetExperienceViewResponseExtensions {
    personalization?: ContentfulViewDelivery.GetExperienceViewResponseExtensionsPersonalization;
    sourceMap?: ContentfulViewDelivery.GetExperienceViewResponseExtensionsSourceMap;
}
