// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export interface GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentContext {
    app?: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentContextApp;
    campaign?: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentContextCampaign;
    library: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentContextLibrary;
    locale?: string;
    location?: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentContextLocation;
    page?: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentContextPage;
    userAgent?: string;
}
