// This file was auto-generated by Fern from our API Definition.

export const GetExperienceViewRequestPreview = {
    True: "true",
    False: "false",
} as const;
export type GetExperienceViewRequestPreview =
    (typeof GetExperienceViewRequestPreview)[keyof typeof GetExperienceViewRequestPreview];
