// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export interface GetExperienceWithOverridesViewResponseSys {
    id: string;
    type: "Experience";
    space: ContentfulViewDelivery.GetExperienceWithOverridesViewResponseSysSpace;
    environment: ContentfulViewDelivery.GetExperienceWithOverridesViewResponseSysEnvironment;
    template: ContentfulViewDelivery.GetExperienceWithOverridesViewResponseSysTemplate;
    createdAt: string;
    updatedAt: string;
    archivedAt?: string;
    archivedBy?: ContentfulViewDelivery.GetExperienceWithOverridesViewResponseSysArchivedBy;
    archivedVersion?: number;
    createdBy: ContentfulViewDelivery.GetExperienceWithOverridesViewResponseSysCreatedBy;
    updatedBy: ContentfulViewDelivery.GetExperienceWithOverridesViewResponseSysUpdatedBy;
    variant?: string;
    variantType?: string;
    variantDimension?: string;
    publishedAt?: string;
    publishedVersion?: number;
    publishedCounter?: number;
    firstPublishedAt?: string;
    publishedBy?: ContentfulViewDelivery.GetExperienceWithOverridesViewResponseSysPublishedBy;
    localeStatus?: Record<string, ContentfulViewDelivery.GetExperienceWithOverridesViewResponseSysLocaleStatusValue>;
    /** Accepts any additional properties */
    [key: string]: any;
}
