// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export interface GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContext {
    app?: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextApp;
    campaign?: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextCampaign;
    library: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextLibrary;
    locale?: string;
    location?: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextLocation;
    page?: ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextPage;
    userAgent?: string;
}
