// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export type GetExperienceWithOverridesViewResponseExtensionsSourceMapLayersItem =
    | ContentfulViewDelivery.GetExperienceWithOverridesViewResponseExtensionsSourceMapLayersItem.ComponentType
    | ContentfulViewDelivery.GetExperienceWithOverridesViewResponseExtensionsSourceMapLayersItem.Template
    | ContentfulViewDelivery.GetExperienceWithOverridesViewResponseExtensionsSourceMapLayersItem.Slot
    | ContentfulViewDelivery.GetExperienceWithOverridesViewResponseExtensionsSourceMapLayersItem.Experience
    | ContentfulViewDelivery.GetExperienceWithOverridesViewResponseExtensionsSourceMapLayersItem.Fragment
    | ContentfulViewDelivery.GetExperienceWithOverridesViewResponseExtensionsSourceMapLayersItem.InlineFragment;

export namespace GetExperienceWithOverridesViewResponseExtensionsSourceMapLayersItem {
    export interface ComponentType
        extends ContentfulViewDelivery.GetExperienceWithOverridesViewResponseExtensionsSourceMapLayersItemComponentType {
        kind: "ComponentType";
    }

    export interface Template
        extends ContentfulViewDelivery.GetExperienceWithOverridesViewResponseExtensionsSourceMapLayersItemTemplate {
        kind: "Template";
    }

    export interface Slot
        extends ContentfulViewDelivery.GetExperienceWithOverridesViewResponseExtensionsSourceMapLayersItemSlot {
        kind: "Slot";
    }

    export interface Experience
        extends ContentfulViewDelivery.GetExperienceWithOverridesViewResponseExtensionsSourceMapLayersItemExperience {
        kind: "Experience";
    }

    export interface Fragment
        extends ContentfulViewDelivery.GetExperienceWithOverridesViewResponseExtensionsSourceMapLayersItemFragment {
        kind: "Fragment";
    }

    export interface InlineFragment
        extends ContentfulViewDelivery.GetExperienceWithOverridesViewResponseExtensionsSourceMapLayersItemInlineFragment {
        kind: "InlineFragment";
    }
}
