// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export interface GetFragmentFragmentResponseExtensionsPersonalizationChangesItemExperience {
    id: string;
    variantId: string;
    meta: ContentfulViewDelivery.GetFragmentFragmentResponseExtensionsPersonalizationChangesItemExperienceMeta;
}
