// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export interface GetFragmentFragmentResponseExtensionsPersonalizationChangesItemFragment {
    id: string;
    variantId: string;
    meta: ContentfulViewDelivery.GetFragmentFragmentResponseExtensionsPersonalizationChangesItemFragmentMeta;
}
