// This file was auto-generated by Fern from our API Definition.

export const GetFragmentFragmentRequestPreview = {
    True: "true",
    False: "false",
} as const;
export type GetFragmentFragmentRequestPreview =
    (typeof GetFragmentFragmentRequestPreview)[keyof typeof GetFragmentFragmentRequestPreview];
