// This file was auto-generated by Fern from our API Definition.

export interface GetFragmentFragmentResponseExtensionsPersonalizationChangesItemExperienceMeta {
    optimizationId: string;
    variantIndex: number;
}
