// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export type GetFragmentFragmentResponseExtensionsPersonalizationChangesItem =
    | ContentfulViewDelivery.GetFragmentFragmentResponseExtensionsPersonalizationChangesItem.Experience
    | ContentfulViewDelivery.GetFragmentFragmentResponseExtensionsPersonalizationChangesItem.Fragment;

export namespace GetFragmentFragmentResponseExtensionsPersonalizationChangesItem {
    export interface Experience
        extends ContentfulViewDelivery.GetFragmentFragmentResponseExtensionsPersonalizationChangesItemExperience {
        type: "Experience";
    }

    export interface Fragment
        extends ContentfulViewDelivery.GetFragmentFragmentResponseExtensionsPersonalizationChangesItemFragment {
        type: "Fragment";
    }
}
