// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../index.js";

/**
 * @example
 *     {
 *         preview: "true",
 *         accessToken: "access_token",
 *         optimizationProfileId: "optimization-profile-id",
 *         locale: "locale",
 *         variant: "variant"
 *     }
 */
export interface GetWithOverridesExperienceRequest {
    preview?: string;
    accessToken?: string;
    optimizationProfileId?: string;
    locale?: string;
    variant?: string;
    extensions?: ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensions;
}
