// This file was auto-generated by Fern from our API Definition.

export const GetExperienceRequestPreview = {
    True: "true",
    False: "false",
} as const;
export type GetExperienceRequestPreview =
    (typeof GetExperienceRequestPreview)[keyof typeof GetExperienceRequestPreview];
