// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export interface GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextLocation {
    coordinates?: ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextLocationCoordinates;
    city?: string;
    postalCode?: string;
    region?: string;
    regionCode?: string;
    country?: string;
    countryCode?: string;
    continent?: string;
    timezone?: string;
}
