// This file was auto-generated by Fern from our API Definition.

export const GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemIdentifyChannel = {
    Web: "web",
    Mobile: "mobile",
    Server: "server",
    Client: "client",
} as const;
export type GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemIdentifyChannel =
    (typeof GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemIdentifyChannel)[keyof typeof GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemIdentifyChannel];
