// This file was auto-generated by Fern from our API Definition.

export interface GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextCampaign {
    name?: string;
    source?: string;
    medium?: string;
    term?: string;
    content?: string;
}
