// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export interface GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContext {
    app?: ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextApp;
    campaign?: ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextCampaign;
    library: ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextLibrary;
    locale?: string;
    location?: ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextLocation;
    page?: ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextPage;
    userAgent?: string;
}
