// This file was auto-generated by Fern from our API Definition.

export const GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageChannel = {
    Web: "web",
    Mobile: "mobile",
    Server: "server",
    Client: "client",
} as const;
export type GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageChannel =
    (typeof GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageChannel)[keyof typeof GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageChannel];
