// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export interface GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageProperties {
    path: string;
    query: Record<
        string,
        ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPagePropertiesQueryValue
    >;
    referrer: string;
    search: string;
    url: string;
    title?: string;
    category?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
