// This file was auto-generated by Fern from our API Definition.

export const GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentComponentType = {
    Entry: "Entry",
    Variable: "Variable",
} as const;
export type GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentComponentType =
    (typeof GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentComponentType)[keyof typeof GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentComponentType];
