// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export interface GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContext {
    app?: ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextApp;
    campaign?: ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextCampaign;
    library: ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextLibrary;
    locale?: string;
    location?: ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextLocation;
    page?: ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextPage;
    userAgent?: string;
}
