// This file was auto-generated by Fern from our API Definition.

export const GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentChannel = {
    Web: "web",
    Mobile: "mobile",
    Server: "server",
    Client: "client",
} as const;
export type GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentChannel =
    (typeof GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentChannel)[keyof typeof GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentChannel];
