// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export interface GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextPage {
    path: string;
    query: Record<
        string,
        ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextPageQueryValue
    >;
    referrer: string;
    search: string;
    url: string;
}
