// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../index.js";

export interface GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemIdentifyContextPage {
    path: string;
    query: Record<
        string,
        ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemIdentifyContextPageQueryValue
    >;
    referrer: string;
    search: string;
    url: string;
}
