// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../index.js";

/**
 * @example
 *     {
 *         path: "/products"
 *     }
 */
export interface DestinationExperiencesByPathRequest {
    /** Absolute path to resolve. Must start with `/`. */
    path: string;
    extensions?: ContentfulViewDelivery.DestinationExperiencesExtensions;
}
