// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextApp } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextApp.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextCampaign } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextCampaign.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextLibrary } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextLibrary.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextLocation } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextLocation.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextPage } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextPage.js";

export const GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContext: core.serialization.ObjectSchema<
    serializers.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContext.Raw,
    ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContext
> = core.serialization.object({
    app: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextApp.optional(),
    campaign: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextCampaign.optional(),
    library: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextLibrary,
    locale: core.serialization.string().optional(),
    location: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextLocation.optional(),
    page: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextPage.optional(),
    userAgent: core.serialization.string().optional(),
});

export declare namespace GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContext {
    export interface Raw {
        app?: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextApp.Raw | null;
        campaign?: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextCampaign.Raw | null;
        library: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextLibrary.Raw;
        locale?: string | null;
        location?: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextLocation.Raw | null;
        page?: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextPage.Raw | null;
        userAgent?: string | null;
    }
}
