// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItem } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItem.js";

export const GetWithOverridesExperienceRequestExtensionsPersonalization: core.serialization.ObjectSchema<
    serializers.GetWithOverridesExperienceRequestExtensionsPersonalization.Raw,
    ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalization
> = core.serialization.object({
    profileId: core.serialization.string().optional(),
    events: core.serialization.list(GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItem).optional(),
});

export declare namespace GetWithOverridesExperienceRequestExtensionsPersonalization {
    export interface Raw {
        profileId?: string | null;
        events?: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItem.Raw[] | null;
    }
}
