// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetWithOverridesExperienceRequestExtensionsSourceMap: core.serialization.ObjectSchema<
    serializers.GetWithOverridesExperienceRequestExtensionsSourceMap.Raw,
    ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsSourceMap
> = core.serialization.object({});

export declare namespace GetWithOverridesExperienceRequestExtensionsSourceMap {
    export type Raw = {};
}
