// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextPageQueryValue } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextPageQueryValue.js";

export const GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextPage: core.serialization.ObjectSchema<
    serializers.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextPage.Raw,
    ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextPage
> = core.serialization.object({
    path: core.serialization.string(),
    query: core.serialization.record(
        core.serialization.string(),
        GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextPageQueryValue,
    ),
    referrer: core.serialization.string(),
    search: core.serialization.string(),
    url: core.serialization.string(),
});

export declare namespace GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextPage {
    export interface Raw {
        path: string;
        query: Record<
            string,
            GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextPageQueryValue.Raw
        >;
        referrer: string;
        search: string;
        url: string;
    }
}
