// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextApp } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextApp.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextCampaign } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextCampaign.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextLibrary } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextLibrary.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextLocation } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextLocation.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextPage } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextPage.js";

export const GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContext: core.serialization.ObjectSchema<
    serializers.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContext.Raw,
    ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContext
> = core.serialization.object({
    app: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextApp.optional(),
    campaign: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextCampaign.optional(),
    library: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextLibrary,
    locale: core.serialization.string().optional(),
    location: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextLocation.optional(),
    page: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextPage.optional(),
    userAgent: core.serialization.string().optional(),
});

export declare namespace GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContext {
    export interface Raw {
        app?: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextApp.Raw | null;
        campaign?: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextCampaign.Raw | null;
        library: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextLibrary.Raw;
        locale?: string | null;
        location?: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextLocation.Raw | null;
        page?: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextPage.Raw | null;
        userAgent?: string | null;
    }
}
