// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextPageQueryValue: core.serialization.Schema<
    serializers.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextPageQueryValue.Raw,
    ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextPageQueryValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(core.serialization.string()),
]);

export declare namespace GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContextPageQueryValue {
    export type Raw = string | string[];
}
