// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetWithOverridesExperienceRequestPreview: core.serialization.Schema<
    serializers.GetWithOverridesExperienceRequestPreview.Raw,
    ContentfulViewDelivery.GetWithOverridesExperienceRequestPreview
> = core.serialization.enum_(["true", "false"]);

export declare namespace GetWithOverridesExperienceRequestPreview {
    export type Raw = "true" | "false";
}
