// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenChannel } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenChannel.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContext } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContext.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenProperties } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenProperties.js";

export const GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreen: core.serialization.ObjectSchema<
    serializers.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreen.Raw,
    ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreen
> = core.serialization.object({
    channel: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenChannel,
    context: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContext,
    messageId: core.serialization.string(),
    timestamp: core.serialization.string(),
    originalTimestamp: core.serialization.string().optional(),
    sentAt: core.serialization.string().optional(),
    userId: core.serialization.string().optional(),
    properties: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenProperties,
});

export declare namespace GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreen {
    export interface Raw {
        channel: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenChannel.Raw;
        context: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenContext.Raw;
        messageId: string;
        timestamp: string;
        originalTimestamp?: string | null;
        sentAt?: string | null;
        userId?: string | null;
        properties: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenProperties.Raw;
    }
}
