// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextApp } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextApp.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextCampaign } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextCampaign.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextLibrary } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextLibrary.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextLocation } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextLocation.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextPage } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextPage.js";

export const GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContext: core.serialization.ObjectSchema<
    serializers.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContext.Raw,
    ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContext
> = core.serialization.object({
    app: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextApp.optional(),
    campaign: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextCampaign.optional(),
    library: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextLibrary,
    locale: core.serialization.string().optional(),
    location: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextLocation.optional(),
    page: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextPage.optional(),
    userAgent: core.serialization.string().optional(),
});

export declare namespace GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContext {
    export interface Raw {
        app?: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextApp.Raw | null;
        campaign?: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextCampaign.Raw | null;
        library: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextLibrary.Raw;
        locale?: string | null;
        location?: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextLocation.Raw | null;
        page?: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextPage.Raw | null;
        userAgent?: string | null;
    }
}
