// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextApp } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextApp.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextCampaign } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextCampaign.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextLibrary } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextLibrary.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextLocation } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextLocation.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextPage } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextPage.js";

export const GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContext: core.serialization.ObjectSchema<
    serializers.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContext.Raw,
    ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContext
> = core.serialization.object({
    app: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextApp.optional(),
    campaign: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextCampaign.optional(),
    library: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextLibrary,
    locale: core.serialization.string().optional(),
    location: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextLocation.optional(),
    page: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextPage.optional(),
    userAgent: core.serialization.string().optional(),
});

export declare namespace GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContext {
    export interface Raw {
        app?: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextApp.Raw | null;
        campaign?: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextCampaign.Raw | null;
        library: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextLibrary.Raw;
        locale?: string | null;
        location?: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextLocation.Raw | null;
        page?: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemComponentContextPage.Raw | null;
        userAgent?: string | null;
    }
}
