// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { HydratedExperienceView } from "../../../types/HydratedExperienceView.js";
import { HydratedView } from "../../../types/HydratedView.js";

export const GetWithOverridesExperienceResponse: core.serialization.Schema<
    serializers.GetWithOverridesExperienceResponse.Raw,
    ContentfulViewDelivery.GetWithOverridesExperienceResponse
> = core.serialization.undiscriminatedUnion([HydratedView, HydratedExperienceView]);

export declare namespace GetWithOverridesExperienceResponse {
    export type Raw = HydratedView.Raw | HydratedExperienceView.Raw;
}
