// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextLocationCoordinates: core.serialization.ObjectSchema<
    serializers.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextLocationCoordinates.Raw,
    ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextLocationCoordinates
> = core.serialization.object({
    latitude: core.serialization.number(),
    longitude: core.serialization.number(),
});

export declare namespace GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextLocationCoordinates {
    export interface Raw {
        latitude: number;
        longitude: number;
    }
}
