// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPagePropertiesQueryValue } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPagePropertiesQueryValue.js";

export const GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageProperties: core.serialization.ObjectSchema<
    serializers.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageProperties.Raw,
    ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageProperties
> = core.serialization
    .object({
        path: core.serialization.string(),
        query: core.serialization.record(
            core.serialization.string(),
            GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPagePropertiesQueryValue,
        ),
        referrer: core.serialization.string(),
        search: core.serialization.string(),
        url: core.serialization.string(),
        title: core.serialization.string().optional(),
        category: core.serialization.string().optional(),
    })
    .passthrough();

export declare namespace GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageProperties {
    export interface Raw {
        path: string;
        query: Record<
            string,
            GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPagePropertiesQueryValue.Raw
        >;
        referrer: string;
        search: string;
        url: string;
        title?: string | null;
        category?: string | null;
        [key: string]: any;
    }
}
