// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageChannel: core.serialization.Schema<
    serializers.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageChannel.Raw,
    ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageChannel
> = core.serialization.enum_(["web", "mobile", "server", "client"]);

export declare namespace GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageChannel {
    export type Raw = "web" | "mobile" | "server" | "client";
}
