// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextPageQueryValue } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextPageQueryValue.js";

export const GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextPage: core.serialization.ObjectSchema<
    serializers.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextPage.Raw,
    ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextPage
> = core.serialization.object({
    path: core.serialization.string(),
    query: core.serialization.record(
        core.serialization.string(),
        GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextPageQueryValue,
    ),
    referrer: core.serialization.string(),
    search: core.serialization.string(),
    url: core.serialization.string(),
});

export declare namespace GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextPage {
    export interface Raw {
        path: string;
        query: Record<
            string,
            GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemPageContextPageQueryValue.Raw
        >;
        referrer: string;
        search: string;
        url: string;
    }
}
