// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextLocationCoordinates } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextLocationCoordinates.js";

export const GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextLocation: core.serialization.ObjectSchema<
    serializers.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextLocation.Raw,
    ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextLocation
> = core.serialization.object({
    coordinates:
        GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextLocationCoordinates.optional(),
    city: core.serialization.string().optional(),
    postalCode: core.serialization.string().optional(),
    region: core.serialization.string().optional(),
    regionCode: core.serialization.string().optional(),
    country: core.serialization.string().optional(),
    countryCode: core.serialization.string().optional(),
    continent: core.serialization.string().optional(),
    timezone: core.serialization.string().optional(),
});

export declare namespace GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextLocation {
    export interface Raw {
        coordinates?: GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemTrackContextLocationCoordinates.Raw | null;
        city?: string | null;
        postalCode?: string | null;
        region?: string | null;
        regionCode?: string | null;
        country?: string | null;
        countryCode?: string | null;
        continent?: string | null;
        timezone?: string | null;
    }
}
