// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemIdentifyContextPageQueryValue } from "./GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemIdentifyContextPageQueryValue.js";

export const GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemIdentifyContextPage: core.serialization.ObjectSchema<
    serializers.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemIdentifyContextPage.Raw,
    ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemIdentifyContextPage
> = core.serialization.object({
    path: core.serialization.string(),
    query: core.serialization.record(
        core.serialization.string(),
        GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemIdentifyContextPageQueryValue,
    ),
    referrer: core.serialization.string(),
    search: core.serialization.string(),
    url: core.serialization.string(),
});

export declare namespace GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemIdentifyContextPage {
    export interface Raw {
        path: string;
        query: Record<
            string,
            GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemIdentifyContextPageQueryValue.Raw
        >;
        referrer: string;
        search: string;
        url: string;
    }
}
