// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenProperties: core.serialization.ObjectSchema<
    serializers.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenProperties.Raw,
    ContentfulViewDelivery.GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenProperties
> = core.serialization
    .object({
        name: core.serialization.string(),
    })
    .passthrough();

export declare namespace GetWithOverridesExperienceRequestExtensionsPersonalizationEventsItemScreenProperties {
    export interface Raw {
        name: string;
        [key: string]: any;
    }
}
