// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackChannel: core.serialization.Schema<
    serializers.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackChannel.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackChannel
> = core.serialization.enum_(["web", "mobile", "server", "client"]);

export declare namespace GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackChannel {
    export type Raw = "web" | "mobile" | "server" | "client";
}
