// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetExperienceViewResponseExtensionsSourceMapEntriesItem: core.serialization.ObjectSchema<
    serializers.GetExperienceViewResponseExtensionsSourceMapEntriesItem.Raw,
    ContentfulViewDelivery.GetExperienceViewResponseExtensionsSourceMapEntriesItem
> = core.serialization.object({
    space: core.serialization.number(),
    environment: core.serialization.number(),
    id: core.serialization.string(),
});

export declare namespace GetExperienceViewResponseExtensionsSourceMapEntriesItem {
    export interface Raw {
        space: number;
        environment: number;
        id: string;
    }
}
