// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenContextPageQueryValue } from "./GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenContextPageQueryValue.js";

export const GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenContextPage: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenContextPage.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenContextPage
> = core.serialization.object({
    path: core.serialization.string(),
    query: core.serialization.record(
        core.serialization.string(),
        GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenContextPageQueryValue,
    ),
    referrer: core.serialization.string(),
    search: core.serialization.string(),
    url: core.serialization.string(),
});

export declare namespace GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenContextPage {
    export interface Raw {
        path: string;
        query: Record<
            string,
            GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenContextPageQueryValue.Raw
        >;
        referrer: string;
        search: string;
        url: string;
    }
}
