// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceViewResponseExtensionsPersonalizationProfileLocation } from "./GetExperienceViewResponseExtensionsPersonalizationProfileLocation.js";
import { GetExperienceViewResponseExtensionsPersonalizationProfileSession } from "./GetExperienceViewResponseExtensionsPersonalizationProfileSession.js";

export const GetExperienceViewResponseExtensionsPersonalizationProfile: core.serialization.ObjectSchema<
    serializers.GetExperienceViewResponseExtensionsPersonalizationProfile.Raw,
    ContentfulViewDelivery.GetExperienceViewResponseExtensionsPersonalizationProfile
> = core.serialization.object({
    id: core.serialization.string(),
    stableId: core.serialization.string(),
    random: core.serialization.number(),
    audiences: core.serialization.list(core.serialization.string()),
    traits: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    location: GetExperienceViewResponseExtensionsPersonalizationProfileLocation,
    session: GetExperienceViewResponseExtensionsPersonalizationProfileSession,
});

export declare namespace GetExperienceViewResponseExtensionsPersonalizationProfile {
    export interface Raw {
        id: string;
        stableId: string;
        random: number;
        audiences: string[];
        traits: Record<string, unknown>;
        location: GetExperienceViewResponseExtensionsPersonalizationProfileLocation.Raw;
        session: GetExperienceViewResponseExtensionsPersonalizationProfileSession.Raw;
    }
}
