// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextApp } from "./GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextApp.js";
import { GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextCampaign } from "./GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextCampaign.js";
import { GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextLibrary } from "./GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextLibrary.js";
import { GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextLocation } from "./GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextLocation.js";
import { GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextPage } from "./GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextPage.js";

export const GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContext: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContext.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContext
> = core.serialization.object({
    app: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextApp.optional(),
    campaign: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextCampaign.optional(),
    library: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextLibrary,
    locale: core.serialization.string().optional(),
    location: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextLocation.optional(),
    page: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextPage.optional(),
    userAgent: core.serialization.string().optional(),
});

export declare namespace GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContext {
    export interface Raw {
        app?: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextApp.Raw | null;
        campaign?: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextCampaign.Raw | null;
        library: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextLibrary.Raw;
        locale?: string | null;
        location?: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextLocation.Raw | null;
        page?: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextPage.Raw | null;
        userAgent?: string | null;
    }
}
