// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetExperienceWithOverridesViewResponseViewportsItem: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewResponseViewportsItem.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewResponseViewportsItem
> = core.serialization.object({
    id: core.serialization.string(),
    query: core.serialization.string(),
    displayName: core.serialization.string(),
    previewSize: core.serialization.string(),
});

export declare namespace GetExperienceWithOverridesViewResponseViewportsItem {
    export interface Raw {
        id: string;
        query: string;
        displayName: string;
        previewSize: string;
    }
}
