// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentChannel } from "./GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentChannel.js";
import { GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentComponentType } from "./GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentComponentType.js";
import { GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentContext } from "./GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentContext.js";

export const GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponent: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponent.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponent
> = core.serialization.object({
    channel: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentChannel,
    context: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentContext,
    messageId: core.serialization.string(),
    timestamp: core.serialization.string(),
    originalTimestamp: core.serialization.string().optional(),
    sentAt: core.serialization.string().optional(),
    userId: core.serialization.string().optional(),
    componentId: core.serialization.string(),
    componentType:
        GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentComponentType.optional(),
    experienceId: core.serialization.string().optional(),
    variantIndex: core.serialization.number().optional(),
    viewDurationMs: core.serialization.number().optional(),
    viewId: core.serialization.string().optional(),
});

export declare namespace GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponent {
    export interface Raw {
        channel: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentChannel.Raw;
        context: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentContext.Raw;
        messageId: string;
        timestamp: string;
        originalTimestamp?: string | null;
        sentAt?: string | null;
        userId?: string | null;
        componentId: string;
        componentType?: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemComponentComponentType.Raw | null;
        experienceId?: string | null;
        variantIndex?: number | null;
        viewDurationMs?: number | null;
        viewId?: string | null;
    }
}
