// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceViewResponseExtensionsPersonalizationProfileSessionLandingPage } from "./GetExperienceViewResponseExtensionsPersonalizationProfileSessionLandingPage.js";

export const GetExperienceViewResponseExtensionsPersonalizationProfileSession: core.serialization.ObjectSchema<
    serializers.GetExperienceViewResponseExtensionsPersonalizationProfileSession.Raw,
    ContentfulViewDelivery.GetExperienceViewResponseExtensionsPersonalizationProfileSession
> = core.serialization.object({
    id: core.serialization.string().optional(),
    isReturningVisitor: core.serialization.boolean(),
    landingPage: GetExperienceViewResponseExtensionsPersonalizationProfileSessionLandingPage,
    count: core.serialization.number(),
    activeSessionLength: core.serialization.number(),
    averageSessionLength: core.serialization.number(),
});

export declare namespace GetExperienceViewResponseExtensionsPersonalizationProfileSession {
    export interface Raw {
        id?: string | null;
        isReturningVisitor: boolean;
        landingPage: GetExperienceViewResponseExtensionsPersonalizationProfileSessionLandingPage.Raw;
        count: number;
        activeSessionLength: number;
        averageSessionLength: number;
    }
}
