// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageChannel } from "./GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageChannel.js";
import { GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContext } from "./GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContext.js";
import { GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageProperties } from "./GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageProperties.js";

export const GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPage: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPage.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPage
> = core.serialization.object({
    channel: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageChannel,
    context: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContext,
    messageId: core.serialization.string(),
    timestamp: core.serialization.string(),
    originalTimestamp: core.serialization.string().optional(),
    sentAt: core.serialization.string().optional(),
    userId: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    properties: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageProperties,
});

export declare namespace GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPage {
    export interface Raw {
        channel: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageChannel.Raw;
        context: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContext.Raw;
        messageId: string;
        timestamp: string;
        originalTimestamp?: string | null;
        sentAt?: string | null;
        userId?: string | null;
        name?: string | null;
        properties: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageProperties.Raw;
    }
}
