// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceWithOverridesViewResponseSysPublishedBySys } from "./GetExperienceWithOverridesViewResponseSysPublishedBySys.js";

export const GetExperienceWithOverridesViewResponseSysPublishedBy: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewResponseSysPublishedBy.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewResponseSysPublishedBy
> = core.serialization.object({
    sys: GetExperienceWithOverridesViewResponseSysPublishedBySys,
});

export declare namespace GetExperienceWithOverridesViewResponseSysPublishedBy {
    export interface Raw {
        sys: GetExperienceWithOverridesViewResponseSysPublishedBySys.Raw;
    }
}
