// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceWithOverridesViewResponseSysEnvironmentSys } from "./GetExperienceWithOverridesViewResponseSysEnvironmentSys.js";

export const GetExperienceWithOverridesViewResponseSysEnvironment: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewResponseSysEnvironment.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewResponseSysEnvironment
> = core.serialization.object({
    sys: GetExperienceWithOverridesViewResponseSysEnvironmentSys,
});

export declare namespace GetExperienceWithOverridesViewResponseSysEnvironment {
    export interface Raw {
        sys: GetExperienceWithOverridesViewResponseSysEnvironmentSys.Raw;
    }
}
