// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceWithOverridesViewResponseExtensionsPersonalizationProfileLocation } from "./GetExperienceWithOverridesViewResponseExtensionsPersonalizationProfileLocation.js";
import { GetExperienceWithOverridesViewResponseExtensionsPersonalizationProfileSession } from "./GetExperienceWithOverridesViewResponseExtensionsPersonalizationProfileSession.js";

export const GetExperienceWithOverridesViewResponseExtensionsPersonalizationProfile: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewResponseExtensionsPersonalizationProfile.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewResponseExtensionsPersonalizationProfile
> = core.serialization.object({
    id: core.serialization.string(),
    stableId: core.serialization.string(),
    random: core.serialization.number(),
    audiences: core.serialization.list(core.serialization.string()),
    traits: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    location: GetExperienceWithOverridesViewResponseExtensionsPersonalizationProfileLocation,
    session: GetExperienceWithOverridesViewResponseExtensionsPersonalizationProfileSession,
});

export declare namespace GetExperienceWithOverridesViewResponseExtensionsPersonalizationProfile {
    export interface Raw {
        id: string;
        stableId: string;
        random: number;
        audiences: string[];
        traits: Record<string, unknown>;
        location: GetExperienceWithOverridesViewResponseExtensionsPersonalizationProfileLocation.Raw;
        session: GetExperienceWithOverridesViewResponseExtensionsPersonalizationProfileSession.Raw;
    }
}
