// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContextPageQueryValue } from "./GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContextPageQueryValue.js";

export const GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContextPage: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContextPage.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContextPage
> = core.serialization.object({
    path: core.serialization.string(),
    query: core.serialization.record(
        core.serialization.string(),
        GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContextPageQueryValue,
    ),
    referrer: core.serialization.string(),
    search: core.serialization.string(),
    url: core.serialization.string(),
});

export declare namespace GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContextPage {
    export interface Raw {
        path: string;
        query: Record<
            string,
            GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContextPageQueryValue.Raw
        >;
        referrer: string;
        search: string;
        url: string;
    }
}
