// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPagePropertiesQueryValue } from "./GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPagePropertiesQueryValue.js";

export const GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageProperties: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageProperties.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageProperties
> = core.serialization
    .object({
        path: core.serialization.string(),
        query: core.serialization.record(
            core.serialization.string(),
            GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPagePropertiesQueryValue,
        ),
        referrer: core.serialization.string(),
        search: core.serialization.string(),
        url: core.serialization.string(),
        title: core.serialization.string().optional(),
        category: core.serialization.string().optional(),
    })
    .passthrough();

export declare namespace GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageProperties {
    export interface Raw {
        path: string;
        query: Record<
            string,
            GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPagePropertiesQueryValue.Raw
        >;
        referrer: string;
        search: string;
        url: string;
        title?: string | null;
        category?: string | null;
        [key: string]: any;
    }
}
