// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetExperienceViewResponseSysLocaleStatusValue: core.serialization.Schema<
    serializers.GetExperienceViewResponseSysLocaleStatusValue.Raw,
    ContentfulViewDelivery.GetExperienceViewResponseSysLocaleStatusValue
> = core.serialization.enum_(["draft", "published", "changed"]);

export declare namespace GetExperienceViewResponseSysLocaleStatusValue {
    export type Raw = "draft" | "published" | "changed";
}
