// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetExperienceWithOverridesViewResponseExtensionsSourceMapLayersItemExperience: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewResponseExtensionsSourceMapLayersItemExperience.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewResponseExtensionsSourceMapLayersItemExperience
> = core.serialization.object({
    id: core.serialization.string(),
    variants: core.serialization.list(core.serialization.number()),
    dataAssembly: core.serialization.number().optional(),
});

export declare namespace GetExperienceWithOverridesViewResponseExtensionsSourceMapLayersItemExperience {
    export interface Raw {
        id: string;
        variants: number[];
        dataAssembly?: number | null;
    }
}
