// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetExperienceViewResponseErrorsItem: core.serialization.ObjectSchema<
    serializers.GetExperienceViewResponseErrorsItem.Raw,
    ContentfulViewDelivery.GetExperienceViewResponseErrorsItem
> = core.serialization.object({
    fieldPath: core.serialization.string(),
    message: core.serialization.string(),
    originalError: core.serialization.unknown(),
});

export declare namespace GetExperienceViewResponseErrorsItem {
    export interface Raw {
        fieldPath: string;
        message: string;
        originalError?: unknown;
    }
}
