// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContextPageQueryValue: core.serialization.Schema<
    serializers.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContextPageQueryValue.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContextPageQueryValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(core.serialization.string()),
]);

export declare namespace GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemTrackContextPageQueryValue {
    export type Raw = string | string[];
}
