// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextPageQueryValue } from "./GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextPageQueryValue.js";

export const GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextPage: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextPage.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextPage
> = core.serialization.object({
    path: core.serialization.string(),
    query: core.serialization.record(
        core.serialization.string(),
        GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextPageQueryValue,
    ),
    referrer: core.serialization.string(),
    search: core.serialization.string(),
    url: core.serialization.string(),
});

export declare namespace GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextPage {
    export interface Raw {
        path: string;
        query: Record<
            string,
            GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemPageContextPageQueryValue.Raw
        >;
        referrer: string;
        search: string;
        url: string;
    }
}
