// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceViewResponseExtensionsPersonalizationProfileSessionLandingPageQueryValue } from "./GetExperienceViewResponseExtensionsPersonalizationProfileSessionLandingPageQueryValue.js";

export const GetExperienceViewResponseExtensionsPersonalizationProfileSessionLandingPage: core.serialization.ObjectSchema<
    serializers.GetExperienceViewResponseExtensionsPersonalizationProfileSessionLandingPage.Raw,
    ContentfulViewDelivery.GetExperienceViewResponseExtensionsPersonalizationProfileSessionLandingPage
> = core.serialization.object({
    path: core.serialization.string(),
    query: core.serialization.record(
        core.serialization.string(),
        GetExperienceViewResponseExtensionsPersonalizationProfileSessionLandingPageQueryValue,
    ),
    referrer: core.serialization.string(),
    search: core.serialization.string(),
    url: core.serialization.string(),
});

export declare namespace GetExperienceViewResponseExtensionsPersonalizationProfileSessionLandingPage {
    export interface Raw {
        path: string;
        query: Record<
            string,
            GetExperienceViewResponseExtensionsPersonalizationProfileSessionLandingPageQueryValue.Raw
        >;
        referrer: string;
        search: string;
        url: string;
    }
}
