// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";
import { GetExperienceViewResponseDimensionKeyMap } from "./GetExperienceViewResponseDimensionKeyMap.js";
import { GetExperienceViewResponseErrorsItem } from "./GetExperienceViewResponseErrorsItem.js";
import { GetExperienceViewResponseExtensions } from "./GetExperienceViewResponseExtensions.js";
import { GetExperienceViewResponseSys } from "./GetExperienceViewResponseSys.js";
import { GetExperienceViewResponseViewportsItem } from "./GetExperienceViewResponseViewportsItem.js";

export const GetExperienceViewResponse: core.serialization.ObjectSchema<
    serializers.GetExperienceViewResponse.Raw,
    ContentfulViewDelivery.GetExperienceViewResponse
> = core.serialization.object({
    sys: GetExperienceViewResponseSys,
    viewports: core.serialization.list(GetExperienceViewResponseViewportsItem),
    dimensionKeyMap: GetExperienceViewResponseDimensionKeyMap,
    nodes: core.serialization.list(
        core.serialization.lazy(() => serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0),
    ),
    errors: core.serialization.list(GetExperienceViewResponseErrorsItem),
    extensions: GetExperienceViewResponseExtensions.optional(),
});

export declare namespace GetExperienceViewResponse {
    export interface Raw {
        sys: GetExperienceViewResponseSys.Raw;
        viewports: GetExperienceViewResponseViewportsItem.Raw[];
        dimensionKeyMap: GetExperienceViewResponseDimensionKeyMap.Raw;
        nodes: serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0.Raw[];
        errors: GetExperienceViewResponseErrorsItem.Raw[];
        extensions?: GetExperienceViewResponseExtensions.Raw | null;
    }
}
