// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenContextCampaign: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenContextCampaign.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenContextCampaign
> = core.serialization.object({
    name: core.serialization.string().optional(),
    source: core.serialization.string().optional(),
    medium: core.serialization.string().optional(),
    term: core.serialization.string().optional(),
    content: core.serialization.string().optional(),
});

export declare namespace GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenContextCampaign {
    export interface Raw {
        name?: string | null;
        source?: string | null;
        medium?: string | null;
        term?: string | null;
        content?: string | null;
    }
}
