// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceViewResponseSysArchivedBy } from "./GetExperienceViewResponseSysArchivedBy.js";
import { GetExperienceViewResponseSysCreatedBy } from "./GetExperienceViewResponseSysCreatedBy.js";
import { GetExperienceViewResponseSysEnvironment } from "./GetExperienceViewResponseSysEnvironment.js";
import { GetExperienceViewResponseSysLocaleStatusValue } from "./GetExperienceViewResponseSysLocaleStatusValue.js";
import { GetExperienceViewResponseSysPublishedBy } from "./GetExperienceViewResponseSysPublishedBy.js";
import { GetExperienceViewResponseSysSpace } from "./GetExperienceViewResponseSysSpace.js";
import { GetExperienceViewResponseSysTemplate } from "./GetExperienceViewResponseSysTemplate.js";
import { GetExperienceViewResponseSysUpdatedBy } from "./GetExperienceViewResponseSysUpdatedBy.js";

export const GetExperienceViewResponseSys: core.serialization.ObjectSchema<
    serializers.GetExperienceViewResponseSys.Raw,
    ContentfulViewDelivery.GetExperienceViewResponseSys
> = core.serialization
    .object({
        id: core.serialization.string(),
        type: core.serialization.stringLiteral("Experience"),
        space: GetExperienceViewResponseSysSpace,
        environment: GetExperienceViewResponseSysEnvironment,
        template: GetExperienceViewResponseSysTemplate,
        createdAt: core.serialization.string(),
        updatedAt: core.serialization.string(),
        archivedAt: core.serialization.string().optional(),
        archivedBy: GetExperienceViewResponseSysArchivedBy.optional(),
        archivedVersion: core.serialization.number().optional(),
        createdBy: GetExperienceViewResponseSysCreatedBy,
        updatedBy: GetExperienceViewResponseSysUpdatedBy,
        variant: core.serialization.string().optional(),
        variantType: core.serialization.string().optional(),
        variantDimension: core.serialization.string().optional(),
        publishedAt: core.serialization.string().optional(),
        publishedVersion: core.serialization.number().optional(),
        publishedCounter: core.serialization.number().optional(),
        firstPublishedAt: core.serialization.string().optional(),
        publishedBy: GetExperienceViewResponseSysPublishedBy.optional(),
        localeStatus: core.serialization
            .record(core.serialization.string(), GetExperienceViewResponseSysLocaleStatusValue)
            .optional(),
    })
    .passthrough();

export declare namespace GetExperienceViewResponseSys {
    export interface Raw {
        id: string;
        type: "Experience";
        space: GetExperienceViewResponseSysSpace.Raw;
        environment: GetExperienceViewResponseSysEnvironment.Raw;
        template: GetExperienceViewResponseSysTemplate.Raw;
        createdAt: string;
        updatedAt: string;
        archivedAt?: string | null;
        archivedBy?: GetExperienceViewResponseSysArchivedBy.Raw | null;
        archivedVersion?: number | null;
        createdBy: GetExperienceViewResponseSysCreatedBy.Raw;
        updatedBy: GetExperienceViewResponseSysUpdatedBy.Raw;
        variant?: string | null;
        variantType?: string | null;
        variantDimension?: string | null;
        publishedAt?: string | null;
        publishedVersion?: number | null;
        publishedCounter?: number | null;
        firstPublishedAt?: string | null;
        publishedBy?: GetExperienceViewResponseSysPublishedBy.Raw | null;
        localeStatus?: Record<string, GetExperienceViewResponseSysLocaleStatusValue.Raw> | null;
        [key: string]: any;
    }
}
