// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentifyChannel } from "./GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentifyChannel.js";
import { GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentifyContext } from "./GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentifyContext.js";

export const GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentify: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentify.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentify
> = core.serialization.object({
    channel: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentifyChannel,
    context: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentifyContext,
    messageId: core.serialization.string(),
    timestamp: core.serialization.string(),
    originalTimestamp: core.serialization.string().optional(),
    sentAt: core.serialization.string().optional(),
    userId: core.serialization.string(),
    traits: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentify {
    export interface Raw {
        channel: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentifyChannel.Raw;
        context: GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentifyContext.Raw;
        messageId: string;
        timestamp: string;
        originalTimestamp?: string | null;
        sentAt?: string | null;
        userId: string;
        traits: Record<string, unknown>;
    }
}
