// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceViewResponseSysPublishedBySys } from "./GetExperienceViewResponseSysPublishedBySys.js";

export const GetExperienceViewResponseSysPublishedBy: core.serialization.ObjectSchema<
    serializers.GetExperienceViewResponseSysPublishedBy.Raw,
    ContentfulViewDelivery.GetExperienceViewResponseSysPublishedBy
> = core.serialization.object({
    sys: GetExperienceViewResponseSysPublishedBySys,
});

export declare namespace GetExperienceViewResponseSysPublishedBy {
    export interface Raw {
        sys: GetExperienceViewResponseSysPublishedBySys.Raw;
    }
}
