// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetExperienceWithOverridesViewResponseSysLocaleStatusValue: core.serialization.Schema<
    serializers.GetExperienceWithOverridesViewResponseSysLocaleStatusValue.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewResponseSysLocaleStatusValue
> = core.serialization.enum_(["draft", "published", "changed"]);

export declare namespace GetExperienceWithOverridesViewResponseSysLocaleStatusValue {
    export type Raw = "draft" | "published" | "changed";
}
