// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceViewResponseSysArchivedBySys } from "./GetExperienceViewResponseSysArchivedBySys.js";

export const GetExperienceViewResponseSysArchivedBy: core.serialization.ObjectSchema<
    serializers.GetExperienceViewResponseSysArchivedBy.Raw,
    ContentfulViewDelivery.GetExperienceViewResponseSysArchivedBy
> = core.serialization.object({
    sys: GetExperienceViewResponseSysArchivedBySys,
});

export declare namespace GetExperienceViewResponseSysArchivedBy {
    export interface Raw {
        sys: GetExperienceViewResponseSysArchivedBySys.Raw;
    }
}
