// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceViewResponseSysEnvironmentSys } from "./GetExperienceViewResponseSysEnvironmentSys.js";

export const GetExperienceViewResponseSysEnvironment: core.serialization.ObjectSchema<
    serializers.GetExperienceViewResponseSysEnvironment.Raw,
    ContentfulViewDelivery.GetExperienceViewResponseSysEnvironment
> = core.serialization.object({
    sys: GetExperienceViewResponseSysEnvironmentSys,
});

export declare namespace GetExperienceViewResponseSysEnvironment {
    export interface Raw {
        sys: GetExperienceViewResponseSysEnvironmentSys.Raw;
    }
}
