// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceViewResponseSysCreatedBySys } from "./GetExperienceViewResponseSysCreatedBySys.js";

export const GetExperienceViewResponseSysCreatedBy: core.serialization.ObjectSchema<
    serializers.GetExperienceViewResponseSysCreatedBy.Raw,
    ContentfulViewDelivery.GetExperienceViewResponseSysCreatedBy
> = core.serialization.object({
    sys: GetExperienceViewResponseSysCreatedBySys,
});

export declare namespace GetExperienceViewResponseSysCreatedBy {
    export interface Raw {
        sys: GetExperienceViewResponseSysCreatedBySys.Raw;
    }
}
