// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetExperienceViewResponseSysPublishedBySysLinkType: core.serialization.Schema<
    serializers.GetExperienceViewResponseSysPublishedBySysLinkType.Raw,
    ContentfulViewDelivery.GetExperienceViewResponseSysPublishedBySysLinkType
> = core.serialization.enum_(["User", "AppDefinition"]);

export declare namespace GetExperienceViewResponseSysPublishedBySysLinkType {
    export type Raw = "User" | "AppDefinition";
}
