// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceViewResponseSysSpaceSys } from "./GetExperienceViewResponseSysSpaceSys.js";

export const GetExperienceViewResponseSysSpace: core.serialization.ObjectSchema<
    serializers.GetExperienceViewResponseSysSpace.Raw,
    ContentfulViewDelivery.GetExperienceViewResponseSysSpace
> = core.serialization.object({
    sys: GetExperienceViewResponseSysSpaceSys,
});

export declare namespace GetExperienceViewResponseSysSpace {
    export interface Raw {
        sys: GetExperienceViewResponseSysSpaceSys.Raw;
    }
}
