// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetExperienceWithOverridesViewResponseSysSpaceSys: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewResponseSysSpaceSys.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewResponseSysSpaceSys
> = core.serialization.object({
    type: core.serialization.stringLiteral("Link"),
    linkType: core.serialization.stringLiteral("Space"),
    id: core.serialization.string(),
});

export declare namespace GetExperienceWithOverridesViewResponseSysSpaceSys {
    export interface Raw {
        type: "Link";
        linkType: "Space";
        id: string;
    }
}
