// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceWithOverridesViewResponseDimensionKeyMapDesignPropertiesValue } from "./GetExperienceWithOverridesViewResponseDimensionKeyMapDesignPropertiesValue.js";

export const GetExperienceWithOverridesViewResponseDimensionKeyMap: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewResponseDimensionKeyMap.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewResponseDimensionKeyMap
> = core.serialization.object({
    designProperties: core.serialization.record(
        core.serialization.string(),
        GetExperienceWithOverridesViewResponseDimensionKeyMapDesignPropertiesValue,
    ),
});

export declare namespace GetExperienceWithOverridesViewResponseDimensionKeyMap {
    export interface Raw {
        designProperties: Record<
            string,
            GetExperienceWithOverridesViewResponseDimensionKeyMapDesignPropertiesValue.Raw
        >;
    }
}
