// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetExperienceWithOverridesViewResponseSysPublishedBySysLinkType: core.serialization.Schema<
    serializers.GetExperienceWithOverridesViewResponseSysPublishedBySysLinkType.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewResponseSysPublishedBySysLinkType
> = core.serialization.enum_(["User", "AppDefinition"]);

export declare namespace GetExperienceWithOverridesViewResponseSysPublishedBySysLinkType {
    export type Raw = "User" | "AppDefinition";
}
