// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetExperienceWithOverridesViewResponseSysUpdatedBySys } from "./GetExperienceWithOverridesViewResponseSysUpdatedBySys.js";

export const GetExperienceWithOverridesViewResponseSysUpdatedBy: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewResponseSysUpdatedBy.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewResponseSysUpdatedBy
> = core.serialization.object({
    sys: GetExperienceWithOverridesViewResponseSysUpdatedBySys,
});

export declare namespace GetExperienceWithOverridesViewResponseSysUpdatedBy {
    export interface Raw {
        sys: GetExperienceWithOverridesViewResponseSysUpdatedBySys.Raw;
    }
}
