// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetExperienceViewResponseExtensionsSourceMapLayersItemInlineFragment: core.serialization.ObjectSchema<
    serializers.GetExperienceViewResponseExtensionsSourceMapLayersItemInlineFragment.Raw,
    ContentfulViewDelivery.GetExperienceViewResponseExtensionsSourceMapLayersItemInlineFragment
> = core.serialization.object({
    id: core.serialization.string(),
    dataAssembly: core.serialization.number().optional(),
});

export declare namespace GetExperienceViewResponseExtensionsSourceMapLayersItemInlineFragment {
    export interface Raw {
        id: string;
        dataAssembly?: number | null;
    }
}
