// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";
import { GetExperienceWithOverridesViewResponseErrorsItem } from "./GetExperienceWithOverridesViewResponseErrorsItem.js";
import { GetExperienceWithOverridesViewResponseExtensions } from "./GetExperienceWithOverridesViewResponseExtensions.js";
import { GetExperienceWithOverridesViewResponseSys } from "./GetExperienceWithOverridesViewResponseSys.js";
import { GetExperienceWithOverridesViewResponseViewportsItem } from "./GetExperienceWithOverridesViewResponseViewportsItem.js";

export const GetExperienceWithOverridesViewResponse: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewResponse.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewResponse
> = core.serialization.object({
    sys: GetExperienceWithOverridesViewResponseSys,
    viewports: core.serialization.list(GetExperienceWithOverridesViewResponseViewportsItem),
    nodes: core.serialization.list(
        core.serialization.lazy(() => serializers.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0),
    ),
    errors: core.serialization.list(GetExperienceWithOverridesViewResponseErrorsItem),
    extensions: GetExperienceWithOverridesViewResponseExtensions.optional(),
});

export declare namespace GetExperienceWithOverridesViewResponse {
    export interface Raw {
        sys: GetExperienceWithOverridesViewResponseSys.Raw;
        viewports: GetExperienceWithOverridesViewResponseViewportsItem.Raw[];
        nodes: serializers.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0.Raw[];
        errors: GetExperienceWithOverridesViewResponseErrorsItem.Raw[];
        extensions?: GetExperienceWithOverridesViewResponseExtensions.Raw | null;
    }
}
