// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetExperienceViewResponseExtensionsPersonalizationExperiencesItem: core.serialization.ObjectSchema<
    serializers.GetExperienceViewResponseExtensionsPersonalizationExperiencesItem.Raw,
    ContentfulViewDelivery.GetExperienceViewResponseExtensionsPersonalizationExperiencesItem
> = core.serialization.object({
    experienceId: core.serialization.string(),
    variantIndex: core.serialization.number(),
    variants: core.serialization.record(core.serialization.string(), core.serialization.string()),
});

export declare namespace GetExperienceViewResponseExtensionsPersonalizationExperiencesItem {
    export interface Raw {
        experienceId: string;
        variantIndex: number;
        variants: Record<string, string>;
    }
}
