// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenContextPageQueryValue: core.serialization.Schema<
    serializers.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenContextPageQueryValue.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenContextPageQueryValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(core.serialization.string()),
]);

export declare namespace GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemScreenContextPageQueryValue {
    export type Raw = string | string[];
}
