// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetExperienceViewResponseSysEnvironmentSys: core.serialization.ObjectSchema<
    serializers.GetExperienceViewResponseSysEnvironmentSys.Raw,
    ContentfulViewDelivery.GetExperienceViewResponseSysEnvironmentSys
> = core.serialization.object({
    type: core.serialization.stringLiteral("Link"),
    linkType: core.serialization.stringLiteral("Environment"),
    id: core.serialization.string(),
});

export declare namespace GetExperienceViewResponseSysEnvironmentSys {
    export interface Raw {
        type: "Link";
        linkType: "Environment";
        id: string;
    }
}
