// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentifyContextApp: core.serialization.ObjectSchema<
    serializers.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentifyContextApp.Raw,
    ContentfulViewDelivery.GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentifyContextApp
> = core.serialization.object({
    name: core.serialization.string(),
    version: core.serialization.string(),
});

export declare namespace GetExperienceWithOverridesViewRequestExtensionsPersonalizationEventsItemIdentifyContextApp {
    export interface Raw {
        name: string;
        version: string;
    }
}
