// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export interface BadRequestErrorBody {
    sys: ContentfulViewDelivery.BadRequestErrorBodySys;
    message?: string;
    requestId?: string;
    details?: unknown;
    i18NContext?: ContentfulViewDelivery.BadRequestErrorBodyI18NContext;
}
