// This file was auto-generated by Fern from our API Definition.

/**
 * Sys metadata block for a ComponentTypeLink.
 */
export interface ComponentTypeLinkSys {
    type: "ResourceLink";
    linkType: "Contentful:ComponentType";
    urn: string;
}
