// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

/**
 * Link to the Component this node is an instance of (renamed ExO entity shape, SPA-4822).
 */
export interface ComponentLink {
    /** Sys metadata block for a ComponentLink. */
    sys: ContentfulViewDelivery.ComponentLinkSys;
}
