// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export type ConflictErrorBodyI18NContextParametersValue =
    | ContentfulViewDelivery.ConflictErrorBodyI18NContextParametersValue.String
    | ContentfulViewDelivery.ConflictErrorBodyI18NContextParametersValue.Number
    | ContentfulViewDelivery.ConflictErrorBodyI18NContextParametersValue.Date
    | ContentfulViewDelivery.ConflictErrorBodyI18NContextParametersValue.ArrayString
    | ContentfulViewDelivery.ConflictErrorBodyI18NContextParametersValue.ArrayNumber;

export namespace ConflictErrorBodyI18NContextParametersValue {
    export interface String extends ContentfulViewDelivery.ConflictErrorBodyI18NContextParametersValueString {
        type: "string";
    }

    export interface Number extends ContentfulViewDelivery.ConflictErrorBodyI18NContextParametersValueNumber {
        type: "number";
    }

    export interface Date extends ContentfulViewDelivery.ConflictErrorBodyI18NContextParametersValueDate {
        type: "date";
    }

    export interface ArrayString extends ContentfulViewDelivery.ConflictErrorBodyI18NContextParametersValueArrayString {
        type: "array.string";
    }

    export interface ArrayNumber extends ContentfulViewDelivery.ConflictErrorBodyI18NContextParametersValueArrayNumber {
        type: "array.number";
    }
}
