// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export interface ConflictErrorBody {
    sys: ContentfulViewDelivery.ConflictErrorBodySys;
    message?: string;
    requestId?: string;
    details?: unknown;
    i18NContext?: ContentfulViewDelivery.ConflictErrorBodyI18NContext;
}
