// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

/**
 * A design property value -- either a `DesignToken` reference or a `ManualDesignValue` with an explicit value.
 */
export type DesignPropertyValue =
    /**
     * A reference to a design token defined elsewhere in the design system. The value is resolved at render time. */
    | ContentfulViewDelivery.DesignPropertyValue.DesignToken
    /**
     * An explicit, non-tokenised design value (e.g. a CSS color, dimension, or number). */
    | ContentfulViewDelivery.DesignPropertyValue.ManualDesignValue;

export namespace DesignPropertyValue {
    export interface DesignToken extends ContentfulViewDelivery.DesignToken {
        type: "DesignToken";
    }

    export interface ManualDesignValue extends ContentfulViewDelivery.ManualDesignValue {
        type: "ManualDesignValue";
    }
}
