// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

/**
 * Link to the Contentful Environment that owns this resource.
 */
export interface EnvironmentLink {
    /** Sys metadata block for a EnvironmentLink. */
    sys: ContentfulViewDelivery.EnvironmentLinkSys;
}
