// This file was auto-generated by Fern from our API Definition.

/**
 * Sys metadata block for a ExperienceTemplateLink.
 */
export interface ExperienceTemplateLinkSys {
    type: "ResourceLink";
    linkType: "Contentful:ExperienceTemplate";
    urn: string;
}
