// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

/**
 * Link to the Experience Template this node embeds (renamed ExO entity shape, SPA-4822).
 */
export interface ExperienceTemplateLink {
    /** Sys metadata block for a ExperienceTemplateLink. */
    sys: ContentfulViewDelivery.ExperienceTemplateLinkSys;
}
