// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export interface ForbiddenErrorBody {
    sys: ContentfulViewDelivery.ForbiddenErrorBodySys;
    message?: string;
    requestId?: string;
    details?: unknown;
    i18NContext?: ContentfulViewDelivery.ForbiddenErrorBodyI18NContext;
}
