// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export interface GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0DesignPropertiesValueZeroManualDesignValue {
    value: ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0DesignPropertiesValueZeroManualDesignValueValue;
}
