// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export type GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0DesignPropertiesValueTypeValuesValue =
    | ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0DesignPropertiesValueTypeValuesValue.DesignToken
    | ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0DesignPropertiesValueTypeValuesValue.ManualDesignValue;

export namespace GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0DesignPropertiesValueTypeValuesValue {
    export interface DesignToken
        extends ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0DesignPropertiesValueTypeValuesValueDesignToken {
        type: "DesignToken";
    }

    export interface ManualDesignValue
        extends ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0DesignPropertiesValueTypeValuesValueManualDesignValue {
        type: "ManualDesignValue";
    }
}
