// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export interface GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentType {
    componentType: ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeComponentType;
    id?: string;
    contentProperties: Record<string, unknown>;
    designProperties: Record<
        string,
        ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValue
    >;
    slots?: Record<string, ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0[]>;
    contentBindings?: string;
}
