// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export type GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateDesignPropertiesValueTypeValuesValue =
    | ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateDesignPropertiesValueTypeValuesValue.DesignToken
    | ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateDesignPropertiesValueTypeValuesValue.ManualDesignValue;

export namespace GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateDesignPropertiesValueTypeValuesValue {
    export interface DesignToken
        extends ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateDesignPropertiesValueTypeValuesValueDesignToken {
        type: "DesignToken";
    }

    export interface ManualDesignValue
        extends ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateDesignPropertiesValueTypeValuesValueManualDesignValue {
        type: "ManualDesignValue";
    }
}
