// This file was auto-generated by Fern from our API Definition.

export type GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValueValue =
    | string
    | number
    | boolean;
