// This file was auto-generated by Fern from our API Definition.

export interface GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeSys {
    type: "ResourceLink";
    linkType: "Contentful:ComponentType";
    urn: string;
}
