// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export type GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValue =
    | ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueZero
    | ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueType;
