// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export interface GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0Template {
    template: ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateTemplate;
    id?: string;
    contentProperties: Record<string, unknown>;
    designProperties: Record<
        string,
        ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateDesignPropertiesValue
    >;
    slots?: Record<string, ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0[]>;
    contentBindings?: string;
}
