// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export interface GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0DesignPropertiesValueZeroManualDesignValue {
    value: ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0DesignPropertiesValueZeroManualDesignValueValue;
}
