// This file was auto-generated by Fern from our API Definition.

export interface HydratedFragmentViewExtensionsPersonalizationExperiencesItem {
    experienceId: string;
    variantIndex: number;
    variants: Record<string, string>;
}
