// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

/**
 * A single node within a hydrated View's tree (legacy shape). Either a Component instance (`componentType` link) or a nested Experience Template reference (`template` link), with content/design properties and any child slots.
 */
export type HydratedTreeNode =
    /**
     * A `HydratedTreeNode` variant that renders a Component instance. */
    | ContentfulViewDelivery.ComponentTreeNode
    /**
     * A `HydratedTreeNode` variant that embeds an Experience Template. */
    | ContentfulViewDelivery.TemplateTreeNode;
