// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export interface HydratedExperienceFragmentViewExtensionsPersonalizationProfileSession {
    id?: string;
    isReturningVisitor: boolean;
    landingPage: ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsPersonalizationProfileSessionLandingPage;
    count: number;
    activeSessionLength: number;
    averageSessionLength: number;
}
