// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export interface HydratedExperienceViewExtensionsPersonalizationProfile {
    id: string;
    stableId: string;
    random: number;
    audiences: string[];
    traits: Record<string, unknown>;
    location: ContentfulViewDelivery.HydratedExperienceViewExtensionsPersonalizationProfileLocation;
    session: ContentfulViewDelivery.HydratedExperienceViewExtensionsPersonalizationProfileSession;
}
