// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export interface HydratedViewExtensionsSourceMapNodesValue {
    layers: number[];
    scope: number;
    contentProperties: ContentfulViewDelivery.HydratedViewExtensionsSourceMapNodesValueContentPropertiesItem[];
}
