// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export type HydratedExperienceFragmentViewExtensionsSourceMapLayersItem =
    | ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItem.ComponentType
    | ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItem.Template
    | ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItem.Slot
    | ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItem.Experience
    | ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItem.Fragment
    | ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItem.InlineFragment
    | ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItem.Component
    | ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItem.ExperienceTemplate
    | ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItem.ExperienceFragment
    | ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItem.InlineExperienceFragment;

export namespace HydratedExperienceFragmentViewExtensionsSourceMapLayersItem {
    export interface ComponentType
        extends ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItemComponentType {
        kind: "ComponentType";
    }

    export interface Template
        extends ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItemTemplate {
        kind: "Template";
    }

    export interface Slot
        extends ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItemSlot {
        kind: "Slot";
    }

    export interface Experience
        extends ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItemExperience {
        kind: "Experience";
    }

    export interface Fragment
        extends ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItemFragment {
        kind: "Fragment";
    }

    export interface InlineFragment
        extends ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItemInlineFragment {
        kind: "InlineFragment";
    }

    export interface Component
        extends ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItemComponent {
        kind: "Component";
    }

    export interface ExperienceTemplate
        extends ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItemExperienceTemplate {
        kind: "ExperienceTemplate";
    }

    export interface ExperienceFragment
        extends ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItemExperienceFragment {
        kind: "ExperienceFragment";
    }

    export interface InlineExperienceFragment
        extends ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItemInlineExperienceFragment {
        kind: "InlineExperienceFragment";
    }
}
