// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export interface HydratedExperienceViewExtensions {
    personalization?: ContentfulViewDelivery.HydratedExperienceViewExtensionsPersonalization;
    sourceMap?: ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMap;
}
