// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export type HydratedExperienceViewExtensionsSourceMapLayersItem =
    | ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItem.ComponentType
    | ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItem.Template
    | ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItem.Slot
    | ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItem.Experience
    | ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItem.Fragment
    | ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItem.InlineFragment
    | ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItem.Component
    | ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItem.ExperienceTemplate
    | ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItem.ExperienceFragment
    | ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItem.InlineExperienceFragment;

export namespace HydratedExperienceViewExtensionsSourceMapLayersItem {
    export interface ComponentType
        extends ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItemComponentType {
        kind: "ComponentType";
    }

    export interface Template
        extends ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItemTemplate {
        kind: "Template";
    }

    export interface Slot extends ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItemSlot {
        kind: "Slot";
    }

    export interface Experience
        extends ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItemExperience {
        kind: "Experience";
    }

    export interface Fragment
        extends ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItemFragment {
        kind: "Fragment";
    }

    export interface InlineFragment
        extends ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItemInlineFragment {
        kind: "InlineFragment";
    }

    export interface Component
        extends ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItemComponent {
        kind: "Component";
    }

    export interface ExperienceTemplate
        extends ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItemExperienceTemplate {
        kind: "ExperienceTemplate";
    }

    export interface ExperienceFragment
        extends ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItemExperienceFragment {
        kind: "ExperienceFragment";
    }

    export interface InlineExperienceFragment
        extends ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMapLayersItemInlineExperienceFragment {
        kind: "InlineExperienceFragment";
    }
}
