// This file was auto-generated by Fern from our API Definition.

export interface HydratedExperienceFragmentViewExtensionsSourceMapVariantsItem {
    type: "personalization";
    id: string;
    experienceId?: string;
    optimizationId?: string;
    variantId?: string;
    variantIndex?: number;
}
