// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

/**
 * A fully hydrated Contentful Experience Fragment, including the tree nodes that should be rendered (`RenamedHydratedTreeNode`), viewport definitions, and any errors encountered during resolution. Renamed ExO entity shape (SPA-4822) -- preview only.
 */
export interface HydratedExperienceFragmentView {
    /** Standard Contentful sys metadata block for an Experience Fragment: stable identifiers, timestamps, the resource type, and a `component` link. Renamed ExO entity shape (SPA-4822) -- preview only, see `DeliveryFragmentSys` for the legacy counterpart. */
    sys: ContentfulViewDelivery.DeliveryExperienceFragmentSys;
    viewports: ContentfulViewDelivery.Viewport[];
    nodes: ContentfulViewDelivery.RenamedHydratedTreeNode[];
    errors: ContentfulViewDelivery.ResolutionError[];
    extensions?: ContentfulViewDelivery.HydratedExperienceFragmentViewExtensions;
}
