// This file was auto-generated by Fern from our API Definition.

export interface HydratedFragmentViewExtensionsSourceMapLayersItemInlineExperienceFragment {
    id: string;
    dataAssembly?: number;
}
