// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export interface HydratedFragmentViewExtensionsPersonalization {
    profile: ContentfulViewDelivery.HydratedFragmentViewExtensionsPersonalizationProfile;
    experiences: ContentfulViewDelivery.HydratedFragmentViewExtensionsPersonalizationExperiencesItem[];
    changes: ContentfulViewDelivery.HydratedFragmentViewExtensionsPersonalizationChangesItem[];
}
