// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export type HydratedFragmentViewExtensionsSourceMapLayersItem =
    | ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItem.ComponentType
    | ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItem.Template
    | ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItem.Slot
    | ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItem.Experience
    | ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItem.Fragment
    | ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItem.InlineFragment
    | ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItem.Component
    | ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItem.ExperienceTemplate
    | ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItem.ExperienceFragment
    | ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItem.InlineExperienceFragment;

export namespace HydratedFragmentViewExtensionsSourceMapLayersItem {
    export interface ComponentType
        extends ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItemComponentType {
        kind: "ComponentType";
    }

    export interface Template extends ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItemTemplate {
        kind: "Template";
    }

    export interface Slot extends ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItemSlot {
        kind: "Slot";
    }

    export interface Experience
        extends ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItemExperience {
        kind: "Experience";
    }

    export interface Fragment extends ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItemFragment {
        kind: "Fragment";
    }

    export interface InlineFragment
        extends ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItemInlineFragment {
        kind: "InlineFragment";
    }

    export interface Component
        extends ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItemComponent {
        kind: "Component";
    }

    export interface ExperienceTemplate
        extends ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItemExperienceTemplate {
        kind: "ExperienceTemplate";
    }

    export interface ExperienceFragment
        extends ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItemExperienceFragment {
        kind: "ExperienceFragment";
    }

    export interface InlineExperienceFragment
        extends ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItemInlineExperienceFragment {
        kind: "InlineExperienceFragment";
    }
}
