// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

/**
 * A fully hydrated Contentful Studio View (a.k.a. Experience), including the tree nodes that should be rendered (`RenamedHydratedTreeNode`) and any errors encountered during resolution. Renamed ExO entity shape (SPA-4822) -- see `HydratedView` for the legacy counterpart.
 */
export interface HydratedExperienceView {
    /** Standard Contentful sys metadata block: stable identifiers, timestamps, the resource type, and an `experienceTemplate` link. Renamed ExO entity shape (SPA-4822) -- see `DeliveryExperienceSys` for the legacy counterpart. */
    sys: ContentfulViewDelivery.RenamedDeliveryExperienceSys;
    nodes: ContentfulViewDelivery.RenamedHydratedTreeNode[];
    errors: ContentfulViewDelivery.ResolutionError[];
    extensions?: ContentfulViewDelivery.HydratedExperienceViewExtensions;
}
