// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export interface HydratedViewExtensionsPersonalizationProfileSessionLandingPage {
    path: string;
    query: Record<
        string,
        ContentfulViewDelivery.HydratedViewExtensionsPersonalizationProfileSessionLandingPageQueryValue
    >;
    referrer: string;
    search: string;
    url: string;
}
