// This file was auto-generated by Fern from our API Definition.

export interface HydratedViewExtensionsSourceMapLayersItemFragment {
    id: string;
    variants: number[];
    dataAssembly?: number;
}
