// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export type HydratedFragmentViewExtensionsPersonalizationChangesItem =
    | ContentfulViewDelivery.HydratedFragmentViewExtensionsPersonalizationChangesItem.Experience
    | ContentfulViewDelivery.HydratedFragmentViewExtensionsPersonalizationChangesItem.Fragment;

export namespace HydratedFragmentViewExtensionsPersonalizationChangesItem {
    export interface Experience
        extends ContentfulViewDelivery.HydratedFragmentViewExtensionsPersonalizationChangesItemExperience {
        type: "Experience";
    }

    export interface Fragment
        extends ContentfulViewDelivery.HydratedFragmentViewExtensionsPersonalizationChangesItemFragment {
        type: "Fragment";
    }
}
