// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export interface InternalServerErrorBody {
    sys: ContentfulViewDelivery.InternalServerErrorBodySys;
    message?: string;
    requestId?: string;
    details?: unknown;
    i18NContext?: ContentfulViewDelivery.InternalServerErrorBodyI18NContext;
}
