// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export type InternalServerErrorBodyI18NContextParametersValue =
    | ContentfulViewDelivery.InternalServerErrorBodyI18NContextParametersValue.String
    | ContentfulViewDelivery.InternalServerErrorBodyI18NContextParametersValue.Number
    | ContentfulViewDelivery.InternalServerErrorBodyI18NContextParametersValue.Date
    | ContentfulViewDelivery.InternalServerErrorBodyI18NContextParametersValue.ArrayString
    | ContentfulViewDelivery.InternalServerErrorBodyI18NContextParametersValue.ArrayNumber;

export namespace InternalServerErrorBodyI18NContextParametersValue {
    export interface String extends ContentfulViewDelivery.InternalServerErrorBodyI18NContextParametersValueString {
        type: "string";
    }

    export interface Number extends ContentfulViewDelivery.InternalServerErrorBodyI18NContextParametersValueNumber {
        type: "number";
    }

    export interface Date extends ContentfulViewDelivery.InternalServerErrorBodyI18NContextParametersValueDate {
        type: "date";
    }

    export interface ArrayString
        extends ContentfulViewDelivery.InternalServerErrorBodyI18NContextParametersValueArrayString {
        type: "array.string";
    }

    export interface ArrayNumber
        extends ContentfulViewDelivery.InternalServerErrorBodyI18NContextParametersValueArrayNumber {
        type: "array.number";
    }
}
