// This file was auto-generated by Fern from our API Definition.

/** Publication status of a locale (`draft`, `published`, or `changed`). */
export const LocaleStatusValue = {
    Draft: "draft",
    Published: "published",
    Changed: "changed",
} as const;
export type LocaleStatusValue = (typeof LocaleStatusValue)[keyof typeof LocaleStatusValue];
