// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

/**
 * An explicit, non-tokenised design value (e.g. a CSS color, dimension, or number).
 */
export interface ManualDesignValue {
    /** A primitive value (string, number, or boolean) used as the explicit design value. */
    value: ContentfulViewDelivery.ManualDesignValuePrimitive;
}
