// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export type NotFoundErrorBodyI18NContextParametersValue =
    | ContentfulViewDelivery.NotFoundErrorBodyI18NContextParametersValue.String
    | ContentfulViewDelivery.NotFoundErrorBodyI18NContextParametersValue.Number
    | ContentfulViewDelivery.NotFoundErrorBodyI18NContextParametersValue.Date
    | ContentfulViewDelivery.NotFoundErrorBodyI18NContextParametersValue.ArrayString
    | ContentfulViewDelivery.NotFoundErrorBodyI18NContextParametersValue.ArrayNumber;

export namespace NotFoundErrorBodyI18NContextParametersValue {
    export interface String extends ContentfulViewDelivery.NotFoundErrorBodyI18NContextParametersValueString {
        type: "string";
    }

    export interface Number extends ContentfulViewDelivery.NotFoundErrorBodyI18NContextParametersValueNumber {
        type: "number";
    }

    export interface Date extends ContentfulViewDelivery.NotFoundErrorBodyI18NContextParametersValueDate {
        type: "date";
    }

    export interface ArrayString extends ContentfulViewDelivery.NotFoundErrorBodyI18NContextParametersValueArrayString {
        type: "array.string";
    }

    export interface ArrayNumber extends ContentfulViewDelivery.NotFoundErrorBodyI18NContextParametersValueArrayNumber {
        type: "array.number";
    }
}
