// This file was auto-generated by Fern from our API Definition.

export interface PersonalizationPageEventProperties {
    path: string;
    query: string;
    referrer: string;
    search: string;
    url: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
