// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

/**
 * Fields shared by personalization events.
 */
export interface PersonalizationEventBase {
    channel: ContentfulViewDelivery.PersonalizationEventBaseChannel;
    /** Event context, including client library information. */
    context: ContentfulViewDelivery.PersonalizationEventBaseContext;
    messageId: string;
    timestamp: string;
    originalTimestamp?: string;
    sentAt?: string;
    userId?: string;
    type: ContentfulViewDelivery.PersonalizationEventBaseType;
    name?: string;
    event?: string;
    properties?: Record<string, unknown>;
    traits?: Record<string, unknown>;
    componentId?: string;
    componentType?: ContentfulViewDelivery.PersonalizationEventBaseComponentType;
    experienceId?: string;
    variantIndex?: number;
    viewDurationMs?: number;
    viewId?: string;
}
