// This file was auto-generated by Fern from our API Definition.

export const PersonalizationEventBaseComponentType = {
    Entry: "Entry",
    Variable: "Variable",
} as const;
export type PersonalizationEventBaseComponentType =
    (typeof PersonalizationEventBaseComponentType)[keyof typeof PersonalizationEventBaseComponentType];
