// This file was auto-generated by Fern from our API Definition.

export const PersonalizationEventBaseChannel = {
    Web: "web",
    Mobile: "mobile",
    Server: "server",
    Client: "client",
} as const;
export type PersonalizationEventBaseChannel =
    (typeof PersonalizationEventBaseChannel)[keyof typeof PersonalizationEventBaseChannel];
