// This file was auto-generated by Fern from our API Definition.

export const PersonalizationEventBaseType = {
    Page: "page",
    Track: "track",
    Identify: "identify",
    Screen: "screen",
    Component: "component",
} as const;
export type PersonalizationEventBaseType =
    (typeof PersonalizationEventBaseType)[keyof typeof PersonalizationEventBaseType];
