// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

/**
 * Personalization event supplied while resolving an Experience.
 */
export type PersonalizationEvent =
    | ContentfulViewDelivery.PersonalizationPageEvent
    | ContentfulViewDelivery.PersonalizationTrackEvent
    | ContentfulViewDelivery.PersonalizationIdentifyEvent
    | ContentfulViewDelivery.PersonalizationScreenEvent
    | ContentfulViewDelivery.PersonalizationComponentEvent;
