// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export type PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValue =
    | ContentfulViewDelivery.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueZero
    | ContentfulViewDelivery.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueType;
