// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export type PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueZero =
    | ContentfulViewDelivery.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueZero.DesignToken
    | ContentfulViewDelivery.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueZero.ManualDesignValue;

export namespace PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueZero {
    export interface DesignToken
        extends ContentfulViewDelivery.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueZeroDesignToken {
        type: "DesignToken";
    }

    export interface ManualDesignValue
        extends ContentfulViewDelivery.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueZeroManualDesignValue {
        type: "ManualDesignValue";
    }
}
