// This file was auto-generated by Fern from our API Definition.

export type PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueTypeValuesValueManualDesignValueValue =
    | string
    | number
    | boolean;
