// This file was auto-generated by Fern from our API Definition.

export interface PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateTemplateSys {
    type: "ResourceLink";
    linkType: "Contentful:Template";
    urn: string;
}
