// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export interface PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueZeroManualDesignValue {
    value: ContentfulViewDelivery.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueZeroManualDesignValueValue;
}
