// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export type PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0 =
    | ContentfulViewDelivery.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentType
    | ContentfulViewDelivery.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0Template;
