// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

/**
 * A `RenamedHydratedTreeNode` variant that renders a Component instance (renamed ExO entity shape, SPA-4822).
 */
export interface RenamedComponentTreeNode {
    /** Link to the Component this node is an instance of (renamed ExO entity shape, SPA-4822). */
    component: ContentfulViewDelivery.ComponentLink;
    id?: string;
    contentProperties: Record<string, unknown>;
    designProperties: Record<string, ContentfulViewDelivery.TreeNodeDesignProperty>;
    slots?: Record<string, ContentfulViewDelivery.RenamedHydratedTreeNode[]>;
    contentBindings?: string;
}
