// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

/**
 * Standard Contentful sys metadata block: stable identifiers, timestamps, the resource type, and an `experienceTemplate` link. Renamed ExO entity shape (SPA-4822) -- see `DeliveryExperienceSys` for the legacy counterpart.
 */
export interface RenamedDeliveryExperienceSys {
    id: string;
    type: "Experience";
    /** Link to the Contentful Space that owns this resource. */
    space: ContentfulViewDelivery.SpaceLink;
    /** Link to the Contentful Environment that owns this resource. */
    environment: ContentfulViewDelivery.EnvironmentLink;
    createdAt: string;
    updatedAt: string;
    archivedAt?: string;
    /** Link to a Contentful User (or AppDefinition) responsible for the action. */
    archivedBy?: ContentfulViewDelivery.UserLink;
    archivedVersion?: number;
    /** Link to a Contentful User (or AppDefinition) responsible for the action. */
    createdBy: ContentfulViewDelivery.UserLink;
    /** Link to a Contentful User (or AppDefinition) responsible for the action. */
    updatedBy: ContentfulViewDelivery.UserLink;
    variant?: string;
    variantType?: string;
    variantDimension?: string;
    publishedAt?: string;
    publishedVersion?: number;
    publishedCounter?: number;
    firstPublishedAt?: string;
    /** Link to a Contentful User (or AppDefinition) responsible for the action. */
    publishedBy?: ContentfulViewDelivery.UserLink;
    localeStatus?: Record<string, ContentfulViewDelivery.LocaleStatusValue>;
    /** Link to the Experience Template this node embeds (renamed ExO entity shape, SPA-4822). */
    experienceTemplate: ContentfulViewDelivery.ExperienceTemplateLink;
    /** Accepts any additional properties */
    [key: string]: any;
}
