// This file was auto-generated by Fern from our API Definition.

/**
 * Sys metadata block for a TemplateLink.
 */
export interface TemplateLinkSys {
    type: "ResourceLink";
    linkType: "Contentful:Template";
    urn: string;
}
