// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

/**
 * A design property attached to a tree node -- either a single DesignPropertyValue or per-viewport ValuesByViewport.
 */
export type TreeNodeDesignProperty =
    /**
     * A design property value -- either a `DesignToken` reference or a `ManualDesignValue` with an explicit value. */
    | ContentfulViewDelivery.DesignPropertyValue
    /**
     * Per-viewport overrides for a design property. */
    | ContentfulViewDelivery.ValuesByViewport;
