// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export interface UnprocessableEntityErrorBodyI18NContext {
    code: string;
    pluralCount?: number;
    parameters?: Record<string, ContentfulViewDelivery.UnprocessableEntityErrorBodyI18NContextParametersValue>;
}
