// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../index.js";

export type UnprocessableEntityErrorBodyI18NContextParametersValue =
    | ContentfulViewDelivery.UnprocessableEntityErrorBodyI18NContextParametersValue.String
    | ContentfulViewDelivery.UnprocessableEntityErrorBodyI18NContextParametersValue.Number
    | ContentfulViewDelivery.UnprocessableEntityErrorBodyI18NContextParametersValue.Date
    | ContentfulViewDelivery.UnprocessableEntityErrorBodyI18NContextParametersValue.ArrayString
    | ContentfulViewDelivery.UnprocessableEntityErrorBodyI18NContextParametersValue.ArrayNumber;

export namespace UnprocessableEntityErrorBodyI18NContextParametersValue {
    export interface String
        extends ContentfulViewDelivery.UnprocessableEntityErrorBodyI18NContextParametersValueString {
        type: "string";
    }

    export interface Number
        extends ContentfulViewDelivery.UnprocessableEntityErrorBodyI18NContextParametersValueNumber {
        type: "number";
    }

    export interface Date extends ContentfulViewDelivery.UnprocessableEntityErrorBodyI18NContextParametersValueDate {
        type: "date";
    }

    export interface ArrayString
        extends ContentfulViewDelivery.UnprocessableEntityErrorBodyI18NContextParametersValueArrayString {
        type: "array.string";
    }

    export interface ArrayNumber
        extends ContentfulViewDelivery.UnprocessableEntityErrorBodyI18NContextParametersValueArrayNumber {
        type: "array.number";
    }
}
