// This file was auto-generated by Fern from our API Definition.

/** Link target type -- either a `User` or an `AppDefinition`. */
export const UserOrAppDefinitionLinkType = {
    User: "User",
    AppDefinition: "AppDefinition",
} as const;
export type UserOrAppDefinitionLinkType =
    (typeof UserOrAppDefinitionLinkType)[keyof typeof UserOrAppDefinitionLinkType];
