// This file was auto-generated by Fern from our API Definition.

/**
 * A viewport breakpoint definition (id, media query, display name, and a preview size used by the Studio renderer).
 */
export interface Viewport {
    id: string;
    query: string;
    displayName: string;
    previewSize: string;
}
