// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { ExperienceClient } from "../resources/experience/client/Client.js";
import { FragmentClient } from "../resources/fragment/client/Client.js";

export declare namespace ReleaseClient {
    export type Options = BaseClientOptions;
}

export class ReleaseClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ReleaseClient.Options>;
    protected _experience: ExperienceClient | undefined;
    protected _fragment: FragmentClient | undefined;

    constructor(options: ReleaseClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get experience(): ExperienceClient {
        return (this._experience ??= new ExperienceClient(this._options));
    }

    public get fragment(): FragmentClient {
        return (this._fragment ??= new FragmentClient(this._options));
    }
}
