// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetFragmentFragmentResponseExtensionsSourceMapDataAssembliesItem: core.serialization.ObjectSchema<
    serializers.GetFragmentFragmentResponseExtensionsSourceMapDataAssembliesItem.Raw,
    ContentfulViewDelivery.GetFragmentFragmentResponseExtensionsSourceMapDataAssembliesItem
> = core.serialization.object({
    id: core.serialization.string(),
    parameters: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    return: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace GetFragmentFragmentResponseExtensionsSourceMapDataAssembliesItem {
    export interface Raw {
        id: string;
        parameters: Record<string, unknown>;
        return: Record<string, unknown>;
    }
}
