// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetFragmentFragmentResponseSysUpdatedBySys } from "./GetFragmentFragmentResponseSysUpdatedBySys.js";

export const GetFragmentFragmentResponseSysUpdatedBy: core.serialization.ObjectSchema<
    serializers.GetFragmentFragmentResponseSysUpdatedBy.Raw,
    ContentfulViewDelivery.GetFragmentFragmentResponseSysUpdatedBy
> = core.serialization.object({
    sys: GetFragmentFragmentResponseSysUpdatedBySys,
});

export declare namespace GetFragmentFragmentResponseSysUpdatedBy {
    export interface Raw {
        sys: GetFragmentFragmentResponseSysUpdatedBySys.Raw;
    }
}
