// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetFragmentFragmentResponseExtensionsPersonalizationChangesItemExperienceMeta } from "./GetFragmentFragmentResponseExtensionsPersonalizationChangesItemExperienceMeta.js";

export const GetFragmentFragmentResponseExtensionsPersonalizationChangesItemExperience: core.serialization.ObjectSchema<
    serializers.GetFragmentFragmentResponseExtensionsPersonalizationChangesItemExperience.Raw,
    ContentfulViewDelivery.GetFragmentFragmentResponseExtensionsPersonalizationChangesItemExperience
> = core.serialization.object({
    id: core.serialization.string(),
    variantId: core.serialization.string(),
    meta: GetFragmentFragmentResponseExtensionsPersonalizationChangesItemExperienceMeta,
});

export declare namespace GetFragmentFragmentResponseExtensionsPersonalizationChangesItemExperience {
    export interface Raw {
        id: string;
        variantId: string;
        meta: GetFragmentFragmentResponseExtensionsPersonalizationChangesItemExperienceMeta.Raw;
    }
}
