// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetFragmentFragmentResponseExtensionsPersonalizationChangesItemExperience } from "./GetFragmentFragmentResponseExtensionsPersonalizationChangesItemExperience.js";
import { GetFragmentFragmentResponseExtensionsPersonalizationChangesItemFragment } from "./GetFragmentFragmentResponseExtensionsPersonalizationChangesItemFragment.js";

export const GetFragmentFragmentResponseExtensionsPersonalizationChangesItem: core.serialization.Schema<
    serializers.GetFragmentFragmentResponseExtensionsPersonalizationChangesItem.Raw,
    ContentfulViewDelivery.GetFragmentFragmentResponseExtensionsPersonalizationChangesItem
> = core.serialization
    .union("type", {
        Experience: GetFragmentFragmentResponseExtensionsPersonalizationChangesItemExperience,
        Fragment: GetFragmentFragmentResponseExtensionsPersonalizationChangesItemFragment,
    })
    .transform<ContentfulViewDelivery.GetFragmentFragmentResponseExtensionsPersonalizationChangesItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace GetFragmentFragmentResponseExtensionsPersonalizationChangesItem {
    export type Raw =
        | GetFragmentFragmentResponseExtensionsPersonalizationChangesItem.Experience
        | GetFragmentFragmentResponseExtensionsPersonalizationChangesItem.Fragment;

    export interface Experience extends GetFragmentFragmentResponseExtensionsPersonalizationChangesItemExperience.Raw {
        type: "Experience";
    }

    export interface Fragment extends GetFragmentFragmentResponseExtensionsPersonalizationChangesItemFragment.Raw {
        type: "Fragment";
    }
}
