// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetFragmentFragmentResponseSysPublishedBySysLinkType: core.serialization.Schema<
    serializers.GetFragmentFragmentResponseSysPublishedBySysLinkType.Raw,
    ContentfulViewDelivery.GetFragmentFragmentResponseSysPublishedBySysLinkType
> = core.serialization.enum_(["User", "AppDefinition"]);

export declare namespace GetFragmentFragmentResponseSysPublishedBySysLinkType {
    export type Raw = "User" | "AppDefinition";
}
