// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetFragmentFragmentResponseExtensionsPersonalizationProfileSessionLandingPage } from "./GetFragmentFragmentResponseExtensionsPersonalizationProfileSessionLandingPage.js";

export const GetFragmentFragmentResponseExtensionsPersonalizationProfileSession: core.serialization.ObjectSchema<
    serializers.GetFragmentFragmentResponseExtensionsPersonalizationProfileSession.Raw,
    ContentfulViewDelivery.GetFragmentFragmentResponseExtensionsPersonalizationProfileSession
> = core.serialization.object({
    id: core.serialization.string().optional(),
    isReturningVisitor: core.serialization.boolean(),
    landingPage: GetFragmentFragmentResponseExtensionsPersonalizationProfileSessionLandingPage,
    count: core.serialization.number(),
    activeSessionLength: core.serialization.number(),
    averageSessionLength: core.serialization.number(),
});

export declare namespace GetFragmentFragmentResponseExtensionsPersonalizationProfileSession {
    export interface Raw {
        id?: string | null;
        isReturningVisitor: boolean;
        landingPage: GetFragmentFragmentResponseExtensionsPersonalizationProfileSessionLandingPage.Raw;
        count: number;
        activeSessionLength: number;
        averageSessionLength: number;
    }
}
