// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetFragmentFragmentResponseSysPublishedBySys } from "./GetFragmentFragmentResponseSysPublishedBySys.js";

export const GetFragmentFragmentResponseSysPublishedBy: core.serialization.ObjectSchema<
    serializers.GetFragmentFragmentResponseSysPublishedBy.Raw,
    ContentfulViewDelivery.GetFragmentFragmentResponseSysPublishedBy
> = core.serialization.object({
    sys: GetFragmentFragmentResponseSysPublishedBySys,
});

export declare namespace GetFragmentFragmentResponseSysPublishedBy {
    export interface Raw {
        sys: GetFragmentFragmentResponseSysPublishedBySys.Raw;
    }
}
