// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetFragmentFragmentResponseExtensionsPersonalizationChangesItem } from "./GetFragmentFragmentResponseExtensionsPersonalizationChangesItem.js";
import { GetFragmentFragmentResponseExtensionsPersonalizationExperiencesItem } from "./GetFragmentFragmentResponseExtensionsPersonalizationExperiencesItem.js";
import { GetFragmentFragmentResponseExtensionsPersonalizationProfile } from "./GetFragmentFragmentResponseExtensionsPersonalizationProfile.js";

export const GetFragmentFragmentResponseExtensionsPersonalization: core.serialization.ObjectSchema<
    serializers.GetFragmentFragmentResponseExtensionsPersonalization.Raw,
    ContentfulViewDelivery.GetFragmentFragmentResponseExtensionsPersonalization
> = core.serialization.object({
    profile: GetFragmentFragmentResponseExtensionsPersonalizationProfile,
    experiences: core.serialization.list(GetFragmentFragmentResponseExtensionsPersonalizationExperiencesItem),
    changes: core.serialization.list(GetFragmentFragmentResponseExtensionsPersonalizationChangesItem),
});

export declare namespace GetFragmentFragmentResponseExtensionsPersonalization {
    export interface Raw {
        profile: GetFragmentFragmentResponseExtensionsPersonalizationProfile.Raw;
        experiences: GetFragmentFragmentResponseExtensionsPersonalizationExperiencesItem.Raw[];
        changes: GetFragmentFragmentResponseExtensionsPersonalizationChangesItem.Raw[];
    }
}
