// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetFragmentFragmentResponseDimensionKeyMapDesignPropertiesValue } from "./GetFragmentFragmentResponseDimensionKeyMapDesignPropertiesValue.js";

export const GetFragmentFragmentResponseDimensionKeyMap: core.serialization.ObjectSchema<
    serializers.GetFragmentFragmentResponseDimensionKeyMap.Raw,
    ContentfulViewDelivery.GetFragmentFragmentResponseDimensionKeyMap
> = core.serialization.object({
    designProperties: core.serialization.record(
        core.serialization.string(),
        GetFragmentFragmentResponseDimensionKeyMapDesignPropertiesValue,
    ),
});

export declare namespace GetFragmentFragmentResponseDimensionKeyMap {
    export interface Raw {
        designProperties: Record<string, GetFragmentFragmentResponseDimensionKeyMapDesignPropertiesValue.Raw>;
    }
}
