// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetFragmentFragmentResponseSysArchivedBySys } from "./GetFragmentFragmentResponseSysArchivedBySys.js";

export const GetFragmentFragmentResponseSysArchivedBy: core.serialization.ObjectSchema<
    serializers.GetFragmentFragmentResponseSysArchivedBy.Raw,
    ContentfulViewDelivery.GetFragmentFragmentResponseSysArchivedBy
> = core.serialization.object({
    sys: GetFragmentFragmentResponseSysArchivedBySys,
});

export declare namespace GetFragmentFragmentResponseSysArchivedBy {
    export interface Raw {
        sys: GetFragmentFragmentResponseSysArchivedBySys.Raw;
    }
}
