// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetFragmentFragmentResponseSysComponentTypeSys } from "./GetFragmentFragmentResponseSysComponentTypeSys.js";

export const GetFragmentFragmentResponseSysComponentType: core.serialization.ObjectSchema<
    serializers.GetFragmentFragmentResponseSysComponentType.Raw,
    ContentfulViewDelivery.GetFragmentFragmentResponseSysComponentType
> = core.serialization.object({
    sys: GetFragmentFragmentResponseSysComponentTypeSys,
});

export declare namespace GetFragmentFragmentResponseSysComponentType {
    export interface Raw {
        sys: GetFragmentFragmentResponseSysComponentTypeSys.Raw;
    }
}
