// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetFragmentFragmentResponseExtensionsPersonalizationChangesItemFragmentMeta } from "./GetFragmentFragmentResponseExtensionsPersonalizationChangesItemFragmentMeta.js";

export const GetFragmentFragmentResponseExtensionsPersonalizationChangesItemFragment: core.serialization.ObjectSchema<
    serializers.GetFragmentFragmentResponseExtensionsPersonalizationChangesItemFragment.Raw,
    ContentfulViewDelivery.GetFragmentFragmentResponseExtensionsPersonalizationChangesItemFragment
> = core.serialization.object({
    id: core.serialization.string(),
    variantId: core.serialization.string(),
    meta: GetFragmentFragmentResponseExtensionsPersonalizationChangesItemFragmentMeta,
});

export declare namespace GetFragmentFragmentResponseExtensionsPersonalizationChangesItemFragment {
    export interface Raw {
        id: string;
        variantId: string;
        meta: GetFragmentFragmentResponseExtensionsPersonalizationChangesItemFragmentMeta.Raw;
    }
}
