// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetFragmentFragmentResponseSysCreatedBySys: core.serialization.ObjectSchema<
    serializers.GetFragmentFragmentResponseSysCreatedBySys.Raw,
    ContentfulViewDelivery.GetFragmentFragmentResponseSysCreatedBySys
> = core.serialization.object({
    type: core.serialization.stringLiteral("Link"),
    linkType: core.serialization.stringLiteral("User"),
    id: core.serialization.string(),
});

export declare namespace GetFragmentFragmentResponseSysCreatedBySys {
    export interface Raw {
        type: "Link";
        linkType: "User";
        id: string;
    }
}
