// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetFragmentFragmentResponseSysArchivedBy } from "./GetFragmentFragmentResponseSysArchivedBy.js";
import { GetFragmentFragmentResponseSysComponentType } from "./GetFragmentFragmentResponseSysComponentType.js";
import { GetFragmentFragmentResponseSysCreatedBy } from "./GetFragmentFragmentResponseSysCreatedBy.js";
import { GetFragmentFragmentResponseSysEnvironment } from "./GetFragmentFragmentResponseSysEnvironment.js";
import { GetFragmentFragmentResponseSysPublishedBy } from "./GetFragmentFragmentResponseSysPublishedBy.js";
import { GetFragmentFragmentResponseSysSpace } from "./GetFragmentFragmentResponseSysSpace.js";
import { GetFragmentFragmentResponseSysUpdatedBy } from "./GetFragmentFragmentResponseSysUpdatedBy.js";

export const GetFragmentFragmentResponseSys: core.serialization.ObjectSchema<
    serializers.GetFragmentFragmentResponseSys.Raw,
    ContentfulViewDelivery.GetFragmentFragmentResponseSys
> = core.serialization
    .object({
        id: core.serialization.string(),
        type: core.serialization.stringLiteral("Fragment"),
        space: GetFragmentFragmentResponseSysSpace,
        environment: GetFragmentFragmentResponseSysEnvironment,
        componentType: GetFragmentFragmentResponseSysComponentType,
        archivedAt: core.serialization.string().optional(),
        archivedBy: GetFragmentFragmentResponseSysArchivedBy.optional(),
        archivedVersion: core.serialization.number().optional(),
        createdAt: core.serialization.string(),
        updatedAt: core.serialization.string(),
        createdBy: GetFragmentFragmentResponseSysCreatedBy,
        updatedBy: GetFragmentFragmentResponseSysUpdatedBy,
        variant: core.serialization.string().optional(),
        variantType: core.serialization.string().optional(),
        variantDimension: core.serialization.string().optional(),
        publishedAt: core.serialization.string().optional(),
        publishedVersion: core.serialization.number().optional(),
        publishedCounter: core.serialization.number().optional(),
        firstPublishedAt: core.serialization.string().optional(),
        publishedBy: GetFragmentFragmentResponseSysPublishedBy.optional(),
    })
    .passthrough();

export declare namespace GetFragmentFragmentResponseSys {
    export interface Raw {
        id: string;
        type: "Fragment";
        space: GetFragmentFragmentResponseSysSpace.Raw;
        environment: GetFragmentFragmentResponseSysEnvironment.Raw;
        componentType: GetFragmentFragmentResponseSysComponentType.Raw;
        archivedAt?: string | null;
        archivedBy?: GetFragmentFragmentResponseSysArchivedBy.Raw | null;
        archivedVersion?: number | null;
        createdAt: string;
        updatedAt: string;
        createdBy: GetFragmentFragmentResponseSysCreatedBy.Raw;
        updatedBy: GetFragmentFragmentResponseSysUpdatedBy.Raw;
        variant?: string | null;
        variantType?: string | null;
        variantDimension?: string | null;
        publishedAt?: string | null;
        publishedVersion?: number | null;
        publishedCounter?: number | null;
        firstPublishedAt?: string | null;
        publishedBy?: GetFragmentFragmentResponseSysPublishedBy.Raw | null;
        [key: string]: any;
    }
}
