// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { BadRequestErrorBodyI18NContextParametersValueArrayNumber } from "./BadRequestErrorBodyI18NContextParametersValueArrayNumber.js";
import { BadRequestErrorBodyI18NContextParametersValueArrayString } from "./BadRequestErrorBodyI18NContextParametersValueArrayString.js";
import { BadRequestErrorBodyI18NContextParametersValueDate } from "./BadRequestErrorBodyI18NContextParametersValueDate.js";
import { BadRequestErrorBodyI18NContextParametersValueNumber } from "./BadRequestErrorBodyI18NContextParametersValueNumber.js";
import { BadRequestErrorBodyI18NContextParametersValueString } from "./BadRequestErrorBodyI18NContextParametersValueString.js";

export const BadRequestErrorBodyI18NContextParametersValue: core.serialization.Schema<
    serializers.BadRequestErrorBodyI18NContextParametersValue.Raw,
    ContentfulViewDelivery.BadRequestErrorBodyI18NContextParametersValue
> = core.serialization
    .union("type", {
        string: BadRequestErrorBodyI18NContextParametersValueString,
        number: BadRequestErrorBodyI18NContextParametersValueNumber,
        date: BadRequestErrorBodyI18NContextParametersValueDate,
        "array.string": BadRequestErrorBodyI18NContextParametersValueArrayString,
        "array.number": BadRequestErrorBodyI18NContextParametersValueArrayNumber,
    })
    .transform<ContentfulViewDelivery.BadRequestErrorBodyI18NContextParametersValue>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace BadRequestErrorBodyI18NContextParametersValue {
    export type Raw =
        | BadRequestErrorBodyI18NContextParametersValue.String
        | BadRequestErrorBodyI18NContextParametersValue.Number
        | BadRequestErrorBodyI18NContextParametersValue.Date
        | BadRequestErrorBodyI18NContextParametersValue.ArrayString
        | BadRequestErrorBodyI18NContextParametersValue.ArrayNumber;

    export interface String extends BadRequestErrorBodyI18NContextParametersValueString.Raw {
        type: "string";
    }

    export interface Number extends BadRequestErrorBodyI18NContextParametersValueNumber.Raw {
        type: "number";
    }

    export interface Date extends BadRequestErrorBodyI18NContextParametersValueDate.Raw {
        type: "date";
    }

    export interface ArrayString extends BadRequestErrorBodyI18NContextParametersValueArrayString.Raw {
        type: "array.string";
    }

    export interface ArrayNumber extends BadRequestErrorBodyI18NContextParametersValueArrayNumber.Raw {
        type: "array.number";
    }
}
