// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ComponentTypeLinkSys } from "./ComponentTypeLinkSys.js";

export const ComponentTypeLink: core.serialization.ObjectSchema<
    serializers.ComponentTypeLink.Raw,
    ContentfulViewDelivery.ComponentTypeLink
> = core.serialization.object({
    sys: ComponentTypeLinkSys,
});

export declare namespace ComponentTypeLink {
    export interface Raw {
        sys: ComponentTypeLinkSys.Raw;
    }
}
