// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ComponentTypeLinkSys: core.serialization.ObjectSchema<
    serializers.ComponentTypeLinkSys.Raw,
    ContentfulViewDelivery.ComponentTypeLinkSys
> = core.serialization.object({
    type: core.serialization.stringLiteral("ResourceLink"),
    linkType: core.serialization.stringLiteral("Contentful:ComponentType"),
    urn: core.serialization.string(),
});

export declare namespace ComponentTypeLinkSys {
    export interface Raw {
        type: "ResourceLink";
        linkType: "Contentful:ComponentType";
        urn: string;
    }
}
