// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConflictErrorBodyI18NContext } from "./ConflictErrorBodyI18NContext.js";
import { ConflictErrorBodySys } from "./ConflictErrorBodySys.js";

export const ConflictErrorBody: core.serialization.ObjectSchema<
    serializers.ConflictErrorBody.Raw,
    ContentfulViewDelivery.ConflictErrorBody
> = core.serialization.object({
    sys: ConflictErrorBodySys,
    message: core.serialization.string().optional(),
    requestId: core.serialization.string().optional(),
    details: core.serialization.unknown().optional(),
    i18NContext: core.serialization.property("i18nContext", ConflictErrorBodyI18NContext.optional()),
});

export declare namespace ConflictErrorBody {
    export interface Raw {
        sys: ConflictErrorBodySys.Raw;
        message?: string | null;
        requestId?: string | null;
        details?: unknown | null;
        i18nContext?: ConflictErrorBodyI18NContext.Raw | null;
    }
}
