// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConflictErrorBodyI18NContextParametersValueArrayNumber } from "./ConflictErrorBodyI18NContextParametersValueArrayNumber.js";
import { ConflictErrorBodyI18NContextParametersValueArrayString } from "./ConflictErrorBodyI18NContextParametersValueArrayString.js";
import { ConflictErrorBodyI18NContextParametersValueDate } from "./ConflictErrorBodyI18NContextParametersValueDate.js";
import { ConflictErrorBodyI18NContextParametersValueNumber } from "./ConflictErrorBodyI18NContextParametersValueNumber.js";
import { ConflictErrorBodyI18NContextParametersValueString } from "./ConflictErrorBodyI18NContextParametersValueString.js";

export const ConflictErrorBodyI18NContextParametersValue: core.serialization.Schema<
    serializers.ConflictErrorBodyI18NContextParametersValue.Raw,
    ContentfulViewDelivery.ConflictErrorBodyI18NContextParametersValue
> = core.serialization
    .union("type", {
        string: ConflictErrorBodyI18NContextParametersValueString,
        number: ConflictErrorBodyI18NContextParametersValueNumber,
        date: ConflictErrorBodyI18NContextParametersValueDate,
        "array.string": ConflictErrorBodyI18NContextParametersValueArrayString,
        "array.number": ConflictErrorBodyI18NContextParametersValueArrayNumber,
    })
    .transform<ContentfulViewDelivery.ConflictErrorBodyI18NContextParametersValue>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace ConflictErrorBodyI18NContextParametersValue {
    export type Raw =
        | ConflictErrorBodyI18NContextParametersValue.String
        | ConflictErrorBodyI18NContextParametersValue.Number
        | ConflictErrorBodyI18NContextParametersValue.Date
        | ConflictErrorBodyI18NContextParametersValue.ArrayString
        | ConflictErrorBodyI18NContextParametersValue.ArrayNumber;

    export interface String extends ConflictErrorBodyI18NContextParametersValueString.Raw {
        type: "string";
    }

    export interface Number extends ConflictErrorBodyI18NContextParametersValueNumber.Raw {
        type: "number";
    }

    export interface Date extends ConflictErrorBodyI18NContextParametersValueDate.Raw {
        type: "date";
    }

    export interface ArrayString extends ConflictErrorBodyI18NContextParametersValueArrayString.Raw {
        type: "array.string";
    }

    export interface ArrayNumber extends ConflictErrorBodyI18NContextParametersValueArrayNumber.Raw {
        type: "array.number";
    }
}
