// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ComponentTypeLink } from "./ComponentTypeLink.js";
import { EnvironmentLink } from "./EnvironmentLink.js";
import { SpaceLink } from "./SpaceLink.js";
import { UserLink } from "./UserLink.js";

export const DeliveryFragmentSys: core.serialization.ObjectSchema<
    serializers.DeliveryFragmentSys.Raw,
    ContentfulViewDelivery.DeliveryFragmentSys
> = core.serialization
    .object({
        id: core.serialization.string(),
        type: core.serialization.stringLiteral("Fragment"),
        space: SpaceLink,
        environment: EnvironmentLink,
        componentType: ComponentTypeLink,
        archivedAt: core.serialization.string().optional(),
        archivedBy: UserLink.optional(),
        archivedVersion: core.serialization.number().optional(),
        createdAt: core.serialization.string(),
        updatedAt: core.serialization.string(),
        createdBy: UserLink,
        updatedBy: UserLink,
        variant: core.serialization.string().optional(),
        variantType: core.serialization.string().optional(),
        variantDimension: core.serialization.string().optional(),
        publishedAt: core.serialization.string().optional(),
        publishedVersion: core.serialization.number().optional(),
        publishedCounter: core.serialization.number().optional(),
        firstPublishedAt: core.serialization.string().optional(),
        publishedBy: UserLink.optional(),
    })
    .passthrough();

export declare namespace DeliveryFragmentSys {
    export interface Raw {
        id: string;
        type: "Fragment";
        space: SpaceLink.Raw;
        environment: EnvironmentLink.Raw;
        componentType: ComponentTypeLink.Raw;
        archivedAt?: string | null;
        archivedBy?: UserLink.Raw | null;
        archivedVersion?: number | null;
        createdAt: string;
        updatedAt: string;
        createdBy: UserLink.Raw;
        updatedBy: UserLink.Raw;
        variant?: string | null;
        variantType?: string | null;
        variantDimension?: string | null;
        publishedAt?: string | null;
        publishedVersion?: number | null;
        publishedCounter?: number | null;
        firstPublishedAt?: string | null;
        publishedBy?: UserLink.Raw | null;
        [key: string]: any;
    }
}
