// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DesignToken: core.serialization.ObjectSchema<
    serializers.DesignToken.Raw,
    ContentfulViewDelivery.DesignToken
> = core.serialization.object({
    value: core.serialization.string(),
});

export declare namespace DesignToken {
    export interface Raw {
        value: string;
    }
}
