// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DestinationSitemapPathsPages: core.serialization.ObjectSchema<
    serializers.DestinationSitemapPathsPages.Raw,
    ContentfulViewDelivery.DestinationSitemapPathsPages
> = core.serialization.object({
    next: core.serialization.string().optional(),
    prev: core.serialization.string().optional(),
});

export declare namespace DestinationSitemapPathsPages {
    export interface Raw {
        next?: string | null;
        prev?: string | null;
    }
}
