// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DestinationSitemapPropertySys: core.serialization.ObjectSchema<
    serializers.DestinationSitemapPropertySys.Raw,
    ContentfulViewDelivery.DestinationSitemapPropertySys
> = core.serialization.object({
    type: core.serialization.stringLiteral("Destination"),
});

export declare namespace DestinationSitemapPropertySys {
    export interface Raw {
        type: "Destination";
    }
}
