// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { DestinationSitemapPaths } from "./DestinationSitemapPaths.js";
import { DestinationSitemapProperty } from "./DestinationSitemapProperty.js";

export const DestinationSitemap: core.serialization.ObjectSchema<
    serializers.DestinationSitemap.Raw,
    ContentfulViewDelivery.DestinationSitemap
> = core.serialization.object({
    property: DestinationSitemapProperty,
    paths: DestinationSitemapPaths,
});

export declare namespace DestinationSitemap {
    export interface Raw {
        property: DestinationSitemapProperty.Raw;
        paths: DestinationSitemapPaths.Raw;
    }
}
