// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ErrorI18NContext: core.serialization.ObjectSchema<
    serializers.ErrorI18NContext.Raw,
    ContentfulViewDelivery.ErrorI18NContext
> = core.serialization.object({
    code: core.serialization.string(),
    pluralCount: core.serialization.number().optional(),
    parameters: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace ErrorI18NContext {
    export interface Raw {
        code: string;
        pluralCount?: number | null;
        parameters?: Record<string, unknown> | null;
    }
}
