// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ExperienceTemplateLinkSys } from "./ExperienceTemplateLinkSys.js";

export const ExperienceTemplateLink: core.serialization.ObjectSchema<
    serializers.ExperienceTemplateLink.Raw,
    ContentfulViewDelivery.ExperienceTemplateLink
> = core.serialization.object({
    sys: ExperienceTemplateLinkSys,
});

export declare namespace ExperienceTemplateLink {
    export interface Raw {
        sys: ExperienceTemplateLinkSys.Raw;
    }
}
