// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ForbiddenErrorBodyI18NContextParametersValueDate: core.serialization.ObjectSchema<
    serializers.ForbiddenErrorBodyI18NContextParametersValueDate.Raw,
    ContentfulViewDelivery.ForbiddenErrorBodyI18NContextParametersValueDate
> = core.serialization.object({
    value: core.serialization.string(),
});

export declare namespace ForbiddenErrorBodyI18NContextParametersValueDate {
    export interface Raw {
        value: string;
    }
}
