// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ForbiddenErrorBodyI18NContextParametersValueArrayNumber: core.serialization.ObjectSchema<
    serializers.ForbiddenErrorBodyI18NContextParametersValueArrayNumber.Raw,
    ContentfulViewDelivery.ForbiddenErrorBodyI18NContextParametersValueArrayNumber
> = core.serialization.object({
    value: core.serialization.list(core.serialization.number()),
});

export declare namespace ForbiddenErrorBodyI18NContextParametersValueArrayNumber {
    export interface Raw {
        value: number[];
    }
}
