// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ForbiddenErrorBodyI18NContextParametersValueArrayNumber } from "./ForbiddenErrorBodyI18NContextParametersValueArrayNumber.js";
import { ForbiddenErrorBodyI18NContextParametersValueArrayString } from "./ForbiddenErrorBodyI18NContextParametersValueArrayString.js";
import { ForbiddenErrorBodyI18NContextParametersValueDate } from "./ForbiddenErrorBodyI18NContextParametersValueDate.js";
import { ForbiddenErrorBodyI18NContextParametersValueNumber } from "./ForbiddenErrorBodyI18NContextParametersValueNumber.js";
import { ForbiddenErrorBodyI18NContextParametersValueString } from "./ForbiddenErrorBodyI18NContextParametersValueString.js";

export const ForbiddenErrorBodyI18NContextParametersValue: core.serialization.Schema<
    serializers.ForbiddenErrorBodyI18NContextParametersValue.Raw,
    ContentfulViewDelivery.ForbiddenErrorBodyI18NContextParametersValue
> = core.serialization
    .union("type", {
        string: ForbiddenErrorBodyI18NContextParametersValueString,
        number: ForbiddenErrorBodyI18NContextParametersValueNumber,
        date: ForbiddenErrorBodyI18NContextParametersValueDate,
        "array.string": ForbiddenErrorBodyI18NContextParametersValueArrayString,
        "array.number": ForbiddenErrorBodyI18NContextParametersValueArrayNumber,
    })
    .transform<ContentfulViewDelivery.ForbiddenErrorBodyI18NContextParametersValue>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace ForbiddenErrorBodyI18NContextParametersValue {
    export type Raw =
        | ForbiddenErrorBodyI18NContextParametersValue.String
        | ForbiddenErrorBodyI18NContextParametersValue.Number
        | ForbiddenErrorBodyI18NContextParametersValue.Date
        | ForbiddenErrorBodyI18NContextParametersValue.ArrayString
        | ForbiddenErrorBodyI18NContextParametersValue.ArrayNumber;

    export interface String extends ForbiddenErrorBodyI18NContextParametersValueString.Raw {
        type: "string";
    }

    export interface Number extends ForbiddenErrorBodyI18NContextParametersValueNumber.Raw {
        type: "number";
    }

    export interface Date extends ForbiddenErrorBodyI18NContextParametersValueDate.Raw {
        type: "date";
    }

    export interface ArrayString extends ForbiddenErrorBodyI18NContextParametersValueArrayString.Raw {
        type: "array.string";
    }

    export interface ArrayNumber extends ForbiddenErrorBodyI18NContextParametersValueArrayNumber.Raw {
        type: "array.number";
    }
}
