// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ForbiddenErrorBodyI18NContextParametersValueArrayString: core.serialization.ObjectSchema<
    serializers.ForbiddenErrorBodyI18NContextParametersValueArrayString.Raw,
    ContentfulViewDelivery.ForbiddenErrorBodyI18NContextParametersValueArrayString
> = core.serialization.object({
    value: core.serialization.list(core.serialization.string()),
});

export declare namespace ForbiddenErrorBodyI18NContextParametersValueArrayString {
    export interface Raw {
        value: string[];
    }
}
