// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ForbiddenErrorBodyI18NContextParametersValue } from "./ForbiddenErrorBodyI18NContextParametersValue.js";

export const ForbiddenErrorBodyI18NContext: core.serialization.ObjectSchema<
    serializers.ForbiddenErrorBodyI18NContext.Raw,
    ContentfulViewDelivery.ForbiddenErrorBodyI18NContext
> = core.serialization.object({
    code: core.serialization.string(),
    pluralCount: core.serialization.number().optional(),
    parameters: core.serialization
        .record(core.serialization.string(), ForbiddenErrorBodyI18NContextParametersValue)
        .optional(),
});

export declare namespace ForbiddenErrorBodyI18NContext {
    export interface Raw {
        code: string;
        pluralCount?: number | null;
        parameters?: Record<string, ForbiddenErrorBodyI18NContextParametersValue.Raw> | null;
    }
}
