// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueDesignToken } from "./GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueDesignToken.js";
import { GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValue } from "./GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValue.js";

export const GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue: core.serialization.Schema<
    serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue.Raw,
    ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue
> = core.serialization
    .union("type", {
        DesignToken:
            GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueDesignToken,
        ManualDesignValue:
            GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValue,
    })
    .transform<ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue>(
        {
            transform: (value) => value,
            untransform: (value) => value,
        },
    );

export declare namespace GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue {
    export type Raw =
        | GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue.DesignToken
        | GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue.ManualDesignValue;

    export interface DesignToken
        extends GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueDesignToken.Raw {
        type: "DesignToken";
    }

    export interface ManualDesignValue
        extends GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValue.Raw {
        type: "ManualDesignValue";
    }
}
