// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZeroDesignToken } from "./GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZeroDesignToken.js";
import { GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZeroManualDesignValue } from "./GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZeroManualDesignValue.js";

export const GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZero: core.serialization.Schema<
    serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZero.Raw,
    ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZero
> = core.serialization
    .union("type", {
        DesignToken:
            GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZeroDesignToken,
        ManualDesignValue:
            GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZeroManualDesignValue,
    })
    .transform<ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZero>(
        {
            transform: (value) => value,
            untransform: (value) => value,
        },
    );

export declare namespace GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZero {
    export type Raw =
        | GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZero.DesignToken
        | GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZero.ManualDesignValue;

    export interface DesignToken
        extends GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZeroDesignToken.Raw {
        type: "DesignToken";
    }

    export interface ManualDesignValue
        extends GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZeroManualDesignValue.Raw {
        type: "ManualDesignValue";
    }
}
