// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateTemplateSys } from "./GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateTemplateSys.js";

export const GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateTemplate: core.serialization.ObjectSchema<
    serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateTemplate.Raw,
    ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateTemplate
> = core.serialization.object({
    sys: GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateTemplateSys,
});

export declare namespace GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateTemplate {
    export interface Raw {
        sys: GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateTemplateSys.Raw;
    }
}
