// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueTypeValuesValueDesignToken } from "./GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueTypeValuesValueDesignToken.js";
import { GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueTypeValuesValueManualDesignValue } from "./GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueTypeValuesValueManualDesignValue.js";

export const GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueTypeValuesValue: core.serialization.Schema<
    serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueTypeValuesValue.Raw,
    ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueTypeValuesValue
> = core.serialization
    .union("type", {
        DesignToken:
            GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueTypeValuesValueDesignToken,
        ManualDesignValue:
            GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueTypeValuesValueManualDesignValue,
    })
    .transform<ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueTypeValuesValue>(
        {
            transform: (value) => value,
            untransform: (value) => value,
        },
    );

export declare namespace GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueTypeValuesValue {
    export type Raw =
        | GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueTypeValuesValue.DesignToken
        | GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueTypeValuesValue.ManualDesignValue;

    export interface DesignToken
        extends GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueTypeValuesValueDesignToken.Raw {
        type: "DesignToken";
    }

    export interface ManualDesignValue
        extends GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueTypeValuesValueManualDesignValue.Raw {
        type: "ManualDesignValue";
    }
}
