// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0DesignPropertiesValueTypeValuesValueManualDesignValueValue } from "./GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0DesignPropertiesValueTypeValuesValueManualDesignValueValue.js";

export const GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0DesignPropertiesValueTypeValuesValueManualDesignValue: core.serialization.ObjectSchema<
    serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0DesignPropertiesValueTypeValuesValueManualDesignValue.Raw,
    ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0DesignPropertiesValueTypeValuesValueManualDesignValue
> = core.serialization.object({
    value: GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0DesignPropertiesValueTypeValuesValueManualDesignValueValue,
});

export declare namespace GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0DesignPropertiesValueTypeValuesValueManualDesignValue {
    export interface Raw {
        value: GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0DesignPropertiesValueTypeValuesValueManualDesignValueValue.Raw;
    }
}
