// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueZeroManualDesignValueValue } from "./GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueZeroManualDesignValueValue.js";

export const GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueZeroManualDesignValue: core.serialization.ObjectSchema<
    serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueZeroManualDesignValue.Raw,
    ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueZeroManualDesignValue
> = core.serialization.object({
    value: GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueZeroManualDesignValueValue,
});

export declare namespace GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueZeroManualDesignValue {
    export interface Raw {
        value: GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0ComponentTypeDesignPropertiesValueZeroManualDesignValueValue.Raw;
    }
}
