// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueDesignToken } from "./GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueDesignToken.js";
import { GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValue } from "./GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValue.js";

export const GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue: core.serialization.Schema<
    serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue.Raw,
    ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue
> = core.serialization
    .union("type", {
        DesignToken:
            GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueDesignToken,
        ManualDesignValue:
            GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValue,
    })
    .transform<ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue>(
        {
            transform: (value) => value,
            untransform: (value) => value,
        },
    );

export declare namespace GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue {
    export type Raw =
        | GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue.DesignToken
        | GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue.ManualDesignValue;

    export interface DesignToken
        extends GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueDesignToken.Raw {
        type: "DesignToken";
    }

    export interface ManualDesignValue
        extends GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValue.Raw {
        type: "ManualDesignValue";
    }
}
