// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZeroManualDesignValueValue } from "./GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZeroManualDesignValueValue.js";

export const GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZeroManualDesignValue: core.serialization.ObjectSchema<
    serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZeroManualDesignValue.Raw,
    ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZeroManualDesignValue
> = core.serialization.object({
    value: GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZeroManualDesignValueValue,
});

export declare namespace GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZeroManualDesignValue {
    export interface Raw {
        value: GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0TemplateDesignPropertiesValueZeroManualDesignValueValue.Raw;
    }
}
