// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0: core.serialization.Schema<
    serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0.Raw,
    ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(
        () => serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentType,
    ),
    core.serialization.lazyObject(
        () => serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0Template,
    ),
]);

export declare namespace GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0 {
    export type Raw =
        | serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentType.Raw
        | serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0Template.Raw;
}
