// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueZeroDesignToken: core.serialization.ObjectSchema<
    serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueZeroDesignToken.Raw,
    ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueZeroDesignToken
> = core.serialization.object({
    value: core.serialization.string(),
});

export declare namespace GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0ComponentTypeDesignPropertiesValueZeroDesignToken {
    export interface Raw {
        value: string;
    }
}
