// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateDesignPropertiesValue } from "./GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateDesignPropertiesValue.js";
import { GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateTemplate } from "./GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateTemplate.js";

export const GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0Template: core.serialization.ObjectSchema<
    serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0Template.Raw,
    ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0Template
> = core.serialization.object({
    template: GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateTemplate,
    id: core.serialization.string().optional(),
    contentProperties: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    designProperties: core.serialization.record(
        core.serialization.string(),
        GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateDesignPropertiesValue,
    ),
    slots: core.serialization
        .record(
            core.serialization.string(),
            core.serialization.list(
                core.serialization.lazy(
                    () => serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0,
                ),
            ),
        )
        .optional(),
    contentBindings: core.serialization.string().optional(),
});

export declare namespace GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0Template {
    export interface Raw {
        template: GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateTemplate.Raw;
        id?: string | null;
        contentProperties: Record<string, unknown>;
        designProperties: Record<
            string,
            GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0TemplateDesignPropertiesValue.Raw
        >;
        slots?: Record<
            string,
            serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdFragmentsId2200Schema0.Raw[]
        > | null;
        contentBindings?: string | null;
    }
}
