// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0DesignPropertiesValueZeroDesignToken } from "./GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0DesignPropertiesValueZeroDesignToken.js";
import { GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0DesignPropertiesValueZeroManualDesignValue } from "./GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0DesignPropertiesValueZeroManualDesignValue.js";

export const GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0DesignPropertiesValueZero: core.serialization.Schema<
    serializers.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0DesignPropertiesValueZero.Raw,
    ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0DesignPropertiesValueZero
> = core.serialization
    .union("type", {
        DesignToken:
            GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0DesignPropertiesValueZeroDesignToken,
        ManualDesignValue:
            GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0DesignPropertiesValueZeroManualDesignValue,
    })
    .transform<ContentfulViewDelivery.GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0DesignPropertiesValueZero>(
        {
            transform: (value) => value,
            untransform: (value) => value,
        },
    );

export declare namespace GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0DesignPropertiesValueZero {
    export type Raw =
        | GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0DesignPropertiesValueZero.DesignToken
        | GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0DesignPropertiesValueZero.ManualDesignValue;

    export interface DesignToken
        extends GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0DesignPropertiesValueZeroDesignToken.Raw {
        type: "DesignToken";
    }

    export interface ManualDesignValue
        extends GetSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId0200Schema0DesignPropertiesValueZeroManualDesignValue.Raw {
        type: "ManualDesignValue";
    }
}
