// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const HydratedExperienceFragmentViewExtensionsPersonalizationChangesItemFragmentMeta: core.serialization.ObjectSchema<
    serializers.HydratedExperienceFragmentViewExtensionsPersonalizationChangesItemFragmentMeta.Raw,
    ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsPersonalizationChangesItemFragmentMeta
> = core.serialization.object({
    optimizationId: core.serialization.string(),
    variantIndex: core.serialization.number(),
});

export declare namespace HydratedExperienceFragmentViewExtensionsPersonalizationChangesItemFragmentMeta {
    export interface Raw {
        optimizationId: string;
        variantIndex: number;
    }
}
