// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const HydratedExperienceFragmentViewExtensionsSourceMapDataAssembliesItem: core.serialization.ObjectSchema<
    serializers.HydratedExperienceFragmentViewExtensionsSourceMapDataAssembliesItem.Raw,
    ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapDataAssembliesItem
> = core.serialization.object({
    id: core.serialization.string(),
    parameters: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    return: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace HydratedExperienceFragmentViewExtensionsSourceMapDataAssembliesItem {
    export interface Raw {
        id: string;
        parameters: Record<string, unknown>;
        return: Record<string, unknown>;
    }
}
