// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedExperienceViewExtensionsPersonalizationChangesItemFragmentMeta } from "./HydratedExperienceViewExtensionsPersonalizationChangesItemFragmentMeta.js";

export const HydratedExperienceViewExtensionsPersonalizationChangesItemFragment: core.serialization.ObjectSchema<
    serializers.HydratedExperienceViewExtensionsPersonalizationChangesItemFragment.Raw,
    ContentfulViewDelivery.HydratedExperienceViewExtensionsPersonalizationChangesItemFragment
> = core.serialization.object({
    id: core.serialization.string(),
    variantId: core.serialization.string(),
    meta: HydratedExperienceViewExtensionsPersonalizationChangesItemFragmentMeta,
});

export declare namespace HydratedExperienceViewExtensionsPersonalizationChangesItemFragment {
    export interface Raw {
        id: string;
        variantId: string;
        meta: HydratedExperienceViewExtensionsPersonalizationChangesItemFragmentMeta.Raw;
    }
}
