// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const HydratedViewExtensionsSourceMapLayersItemComponent: core.serialization.ObjectSchema<
    serializers.HydratedViewExtensionsSourceMapLayersItemComponent.Raw,
    ContentfulViewDelivery.HydratedViewExtensionsSourceMapLayersItemComponent
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace HydratedViewExtensionsSourceMapLayersItemComponent {
    export interface Raw {
        id: string;
    }
}
