// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedViewExtensionsPersonalizationProfileSessionLandingPageQueryValue } from "./HydratedViewExtensionsPersonalizationProfileSessionLandingPageQueryValue.js";

export const HydratedViewExtensionsPersonalizationProfileSessionLandingPage: core.serialization.ObjectSchema<
    serializers.HydratedViewExtensionsPersonalizationProfileSessionLandingPage.Raw,
    ContentfulViewDelivery.HydratedViewExtensionsPersonalizationProfileSessionLandingPage
> = core.serialization.object({
    path: core.serialization.string(),
    query: core.serialization.record(
        core.serialization.string(),
        HydratedViewExtensionsPersonalizationProfileSessionLandingPageQueryValue,
    ),
    referrer: core.serialization.string(),
    search: core.serialization.string(),
    url: core.serialization.string(),
});

export declare namespace HydratedViewExtensionsPersonalizationProfileSessionLandingPage {
    export interface Raw {
        path: string;
        query: Record<string, HydratedViewExtensionsPersonalizationProfileSessionLandingPageQueryValue.Raw>;
        referrer: string;
        search: string;
        url: string;
    }
}
