// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedFragmentViewExtensionsPersonalizationChangesItemExperienceMeta } from "./HydratedFragmentViewExtensionsPersonalizationChangesItemExperienceMeta.js";

export const HydratedFragmentViewExtensionsPersonalizationChangesItemExperience: core.serialization.ObjectSchema<
    serializers.HydratedFragmentViewExtensionsPersonalizationChangesItemExperience.Raw,
    ContentfulViewDelivery.HydratedFragmentViewExtensionsPersonalizationChangesItemExperience
> = core.serialization.object({
    id: core.serialization.string(),
    variantId: core.serialization.string(),
    meta: HydratedFragmentViewExtensionsPersonalizationChangesItemExperienceMeta,
});

export declare namespace HydratedFragmentViewExtensionsPersonalizationChangesItemExperience {
    export interface Raw {
        id: string;
        variantId: string;
        meta: HydratedFragmentViewExtensionsPersonalizationChangesItemExperienceMeta.Raw;
    }
}
