// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedFragmentViewExtensionsSourceMapNodesValueContentPropertiesItem } from "./HydratedFragmentViewExtensionsSourceMapNodesValueContentPropertiesItem.js";

export const HydratedFragmentViewExtensionsSourceMapNodesValue: core.serialization.ObjectSchema<
    serializers.HydratedFragmentViewExtensionsSourceMapNodesValue.Raw,
    ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapNodesValue
> = core.serialization.object({
    layers: core.serialization.list(core.serialization.number()),
    scope: core.serialization.number(),
    contentProperties: core.serialization.list(HydratedFragmentViewExtensionsSourceMapNodesValueContentPropertiesItem),
});

export declare namespace HydratedFragmentViewExtensionsSourceMapNodesValue {
    export interface Raw {
        layers: number[];
        scope: number;
        contentProperties: HydratedFragmentViewExtensionsSourceMapNodesValueContentPropertiesItem.Raw[];
    }
}
