// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const HydratedExperience: core.serialization.ObjectSchema<
    serializers.HydratedExperience.Raw,
    ContentfulViewDelivery.HydratedExperience
> = core.serialization.object({
    sys: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    viewports: core.serialization.list(
        core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    ),
    nodes: core.serialization.list(
        core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    ),
    errors: core.serialization.list(
        core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    ),
    extensions: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    source: core.serialization.property(
        "__source",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    ),
});

export declare namespace HydratedExperience {
    export interface Raw {
        sys: Record<string, unknown>;
        viewports: Record<string, unknown>[];
        nodes: Record<string, unknown>[];
        errors: Record<string, unknown>[];
        extensions?: Record<string, unknown> | null;
        __source?: Record<string, unknown> | null;
    }
}
