// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const HydratedExperienceFragmentViewExtensionsSourceMapLayersItemInlineFragment: core.serialization.ObjectSchema<
    serializers.HydratedExperienceFragmentViewExtensionsSourceMapLayersItemInlineFragment.Raw,
    ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapLayersItemInlineFragment
> = core.serialization.object({
    id: core.serialization.string(),
    dataAssembly: core.serialization.number().optional(),
});

export declare namespace HydratedExperienceFragmentViewExtensionsSourceMapLayersItemInlineFragment {
    export interface Raw {
        id: string;
        dataAssembly?: number | null;
    }
}
