// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedFragmentViewExtensionsSourceMapLayersItemComponent } from "./HydratedFragmentViewExtensionsSourceMapLayersItemComponent.js";
import { HydratedFragmentViewExtensionsSourceMapLayersItemComponentType } from "./HydratedFragmentViewExtensionsSourceMapLayersItemComponentType.js";
import { HydratedFragmentViewExtensionsSourceMapLayersItemExperience } from "./HydratedFragmentViewExtensionsSourceMapLayersItemExperience.js";
import { HydratedFragmentViewExtensionsSourceMapLayersItemExperienceFragment } from "./HydratedFragmentViewExtensionsSourceMapLayersItemExperienceFragment.js";
import { HydratedFragmentViewExtensionsSourceMapLayersItemExperienceTemplate } from "./HydratedFragmentViewExtensionsSourceMapLayersItemExperienceTemplate.js";
import { HydratedFragmentViewExtensionsSourceMapLayersItemFragment } from "./HydratedFragmentViewExtensionsSourceMapLayersItemFragment.js";
import { HydratedFragmentViewExtensionsSourceMapLayersItemInlineExperienceFragment } from "./HydratedFragmentViewExtensionsSourceMapLayersItemInlineExperienceFragment.js";
import { HydratedFragmentViewExtensionsSourceMapLayersItemInlineFragment } from "./HydratedFragmentViewExtensionsSourceMapLayersItemInlineFragment.js";
import { HydratedFragmentViewExtensionsSourceMapLayersItemSlot } from "./HydratedFragmentViewExtensionsSourceMapLayersItemSlot.js";
import { HydratedFragmentViewExtensionsSourceMapLayersItemTemplate } from "./HydratedFragmentViewExtensionsSourceMapLayersItemTemplate.js";

export const HydratedFragmentViewExtensionsSourceMapLayersItem: core.serialization.Schema<
    serializers.HydratedFragmentViewExtensionsSourceMapLayersItem.Raw,
    ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItem
> = core.serialization
    .union("kind", {
        ComponentType: HydratedFragmentViewExtensionsSourceMapLayersItemComponentType,
        Template: HydratedFragmentViewExtensionsSourceMapLayersItemTemplate,
        Slot: HydratedFragmentViewExtensionsSourceMapLayersItemSlot,
        Experience: HydratedFragmentViewExtensionsSourceMapLayersItemExperience,
        Fragment: HydratedFragmentViewExtensionsSourceMapLayersItemFragment,
        InlineFragment: HydratedFragmentViewExtensionsSourceMapLayersItemInlineFragment,
        Component: HydratedFragmentViewExtensionsSourceMapLayersItemComponent,
        ExperienceTemplate: HydratedFragmentViewExtensionsSourceMapLayersItemExperienceTemplate,
        ExperienceFragment: HydratedFragmentViewExtensionsSourceMapLayersItemExperienceFragment,
        InlineExperienceFragment: HydratedFragmentViewExtensionsSourceMapLayersItemInlineExperienceFragment,
    })
    .transform<ContentfulViewDelivery.HydratedFragmentViewExtensionsSourceMapLayersItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace HydratedFragmentViewExtensionsSourceMapLayersItem {
    export type Raw =
        | HydratedFragmentViewExtensionsSourceMapLayersItem.ComponentType
        | HydratedFragmentViewExtensionsSourceMapLayersItem.Template
        | HydratedFragmentViewExtensionsSourceMapLayersItem.Slot
        | HydratedFragmentViewExtensionsSourceMapLayersItem.Experience
        | HydratedFragmentViewExtensionsSourceMapLayersItem.Fragment
        | HydratedFragmentViewExtensionsSourceMapLayersItem.InlineFragment
        | HydratedFragmentViewExtensionsSourceMapLayersItem.Component
        | HydratedFragmentViewExtensionsSourceMapLayersItem.ExperienceTemplate
        | HydratedFragmentViewExtensionsSourceMapLayersItem.ExperienceFragment
        | HydratedFragmentViewExtensionsSourceMapLayersItem.InlineExperienceFragment;

    export interface ComponentType extends HydratedFragmentViewExtensionsSourceMapLayersItemComponentType.Raw {
        kind: "ComponentType";
    }

    export interface Template extends HydratedFragmentViewExtensionsSourceMapLayersItemTemplate.Raw {
        kind: "Template";
    }

    export interface Slot extends HydratedFragmentViewExtensionsSourceMapLayersItemSlot.Raw {
        kind: "Slot";
    }

    export interface Experience extends HydratedFragmentViewExtensionsSourceMapLayersItemExperience.Raw {
        kind: "Experience";
    }

    export interface Fragment extends HydratedFragmentViewExtensionsSourceMapLayersItemFragment.Raw {
        kind: "Fragment";
    }

    export interface InlineFragment extends HydratedFragmentViewExtensionsSourceMapLayersItemInlineFragment.Raw {
        kind: "InlineFragment";
    }

    export interface Component extends HydratedFragmentViewExtensionsSourceMapLayersItemComponent.Raw {
        kind: "Component";
    }

    export interface ExperienceTemplate
        extends HydratedFragmentViewExtensionsSourceMapLayersItemExperienceTemplate.Raw {
        kind: "ExperienceTemplate";
    }

    export interface ExperienceFragment
        extends HydratedFragmentViewExtensionsSourceMapLayersItemExperienceFragment.Raw {
        kind: "ExperienceFragment";
    }

    export interface InlineExperienceFragment
        extends HydratedFragmentViewExtensionsSourceMapLayersItemInlineExperienceFragment.Raw {
        kind: "InlineExperienceFragment";
    }
}
