// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedExperienceViewExtensionsPersonalizationProfileSessionLandingPageQueryValue } from "./HydratedExperienceViewExtensionsPersonalizationProfileSessionLandingPageQueryValue.js";

export const HydratedExperienceViewExtensionsPersonalizationProfileSessionLandingPage: core.serialization.ObjectSchema<
    serializers.HydratedExperienceViewExtensionsPersonalizationProfileSessionLandingPage.Raw,
    ContentfulViewDelivery.HydratedExperienceViewExtensionsPersonalizationProfileSessionLandingPage
> = core.serialization.object({
    path: core.serialization.string(),
    query: core.serialization.record(
        core.serialization.string(),
        HydratedExperienceViewExtensionsPersonalizationProfileSessionLandingPageQueryValue,
    ),
    referrer: core.serialization.string(),
    search: core.serialization.string(),
    url: core.serialization.string(),
});

export declare namespace HydratedExperienceViewExtensionsPersonalizationProfileSessionLandingPage {
    export interface Raw {
        path: string;
        query: Record<string, HydratedExperienceViewExtensionsPersonalizationProfileSessionLandingPageQueryValue.Raw>;
        referrer: string;
        search: string;
        url: string;
    }
}
