// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedFragmentViewExtensionsPersonalizationChangesItemExperience } from "./HydratedFragmentViewExtensionsPersonalizationChangesItemExperience.js";
import { HydratedFragmentViewExtensionsPersonalizationChangesItemFragment } from "./HydratedFragmentViewExtensionsPersonalizationChangesItemFragment.js";

export const HydratedFragmentViewExtensionsPersonalizationChangesItem: core.serialization.Schema<
    serializers.HydratedFragmentViewExtensionsPersonalizationChangesItem.Raw,
    ContentfulViewDelivery.HydratedFragmentViewExtensionsPersonalizationChangesItem
> = core.serialization
    .union("type", {
        Experience: HydratedFragmentViewExtensionsPersonalizationChangesItemExperience,
        Fragment: HydratedFragmentViewExtensionsPersonalizationChangesItemFragment,
    })
    .transform<ContentfulViewDelivery.HydratedFragmentViewExtensionsPersonalizationChangesItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace HydratedFragmentViewExtensionsPersonalizationChangesItem {
    export type Raw =
        | HydratedFragmentViewExtensionsPersonalizationChangesItem.Experience
        | HydratedFragmentViewExtensionsPersonalizationChangesItem.Fragment;

    export interface Experience extends HydratedFragmentViewExtensionsPersonalizationChangesItemExperience.Raw {
        type: "Experience";
    }

    export interface Fragment extends HydratedFragmentViewExtensionsPersonalizationChangesItemFragment.Raw {
        type: "Fragment";
    }
}
