// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedFragmentViewExtensionsPersonalizationProfileSessionLandingPage } from "./HydratedFragmentViewExtensionsPersonalizationProfileSessionLandingPage.js";

export const HydratedFragmentViewExtensionsPersonalizationProfileSession: core.serialization.ObjectSchema<
    serializers.HydratedFragmentViewExtensionsPersonalizationProfileSession.Raw,
    ContentfulViewDelivery.HydratedFragmentViewExtensionsPersonalizationProfileSession
> = core.serialization.object({
    id: core.serialization.string().optional(),
    isReturningVisitor: core.serialization.boolean(),
    landingPage: HydratedFragmentViewExtensionsPersonalizationProfileSessionLandingPage,
    count: core.serialization.number(),
    activeSessionLength: core.serialization.number(),
    averageSessionLength: core.serialization.number(),
});

export declare namespace HydratedFragmentViewExtensionsPersonalizationProfileSession {
    export interface Raw {
        id?: string | null;
        isReturningVisitor: boolean;
        landingPage: HydratedFragmentViewExtensionsPersonalizationProfileSessionLandingPage.Raw;
        count: number;
        activeSessionLength: number;
        averageSessionLength: number;
    }
}
