// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedExperienceFragmentViewExtensionsPersonalizationChangesItemFragmentMeta } from "./HydratedExperienceFragmentViewExtensionsPersonalizationChangesItemFragmentMeta.js";

export const HydratedExperienceFragmentViewExtensionsPersonalizationChangesItemFragment: core.serialization.ObjectSchema<
    serializers.HydratedExperienceFragmentViewExtensionsPersonalizationChangesItemFragment.Raw,
    ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsPersonalizationChangesItemFragment
> = core.serialization.object({
    id: core.serialization.string(),
    variantId: core.serialization.string(),
    meta: HydratedExperienceFragmentViewExtensionsPersonalizationChangesItemFragmentMeta,
});

export declare namespace HydratedExperienceFragmentViewExtensionsPersonalizationChangesItemFragment {
    export interface Raw {
        id: string;
        variantId: string;
        meta: HydratedExperienceFragmentViewExtensionsPersonalizationChangesItemFragmentMeta.Raw;
    }
}
