// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedExperienceViewExtensionsPersonalizationChangesItemExperienceMeta } from "./HydratedExperienceViewExtensionsPersonalizationChangesItemExperienceMeta.js";

export const HydratedExperienceViewExtensionsPersonalizationChangesItemExperience: core.serialization.ObjectSchema<
    serializers.HydratedExperienceViewExtensionsPersonalizationChangesItemExperience.Raw,
    ContentfulViewDelivery.HydratedExperienceViewExtensionsPersonalizationChangesItemExperience
> = core.serialization.object({
    id: core.serialization.string(),
    variantId: core.serialization.string(),
    meta: HydratedExperienceViewExtensionsPersonalizationChangesItemExperienceMeta,
});

export declare namespace HydratedExperienceViewExtensionsPersonalizationChangesItemExperience {
    export interface Raw {
        id: string;
        variantId: string;
        meta: HydratedExperienceViewExtensionsPersonalizationChangesItemExperienceMeta.Raw;
    }
}
