// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedFragmentViewExtensionsPersonalizationChangesItemFragmentMeta } from "./HydratedFragmentViewExtensionsPersonalizationChangesItemFragmentMeta.js";

export const HydratedFragmentViewExtensionsPersonalizationChangesItemFragment: core.serialization.ObjectSchema<
    serializers.HydratedFragmentViewExtensionsPersonalizationChangesItemFragment.Raw,
    ContentfulViewDelivery.HydratedFragmentViewExtensionsPersonalizationChangesItemFragment
> = core.serialization.object({
    id: core.serialization.string(),
    variantId: core.serialization.string(),
    meta: HydratedFragmentViewExtensionsPersonalizationChangesItemFragmentMeta,
});

export declare namespace HydratedFragmentViewExtensionsPersonalizationChangesItemFragment {
    export interface Raw {
        id: string;
        variantId: string;
        meta: HydratedFragmentViewExtensionsPersonalizationChangesItemFragmentMeta.Raw;
    }
}
