// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const HydratedExperienceFragmentViewExtensionsPersonalizationExperiencesItem: core.serialization.ObjectSchema<
    serializers.HydratedExperienceFragmentViewExtensionsPersonalizationExperiencesItem.Raw,
    ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsPersonalizationExperiencesItem
> = core.serialization.object({
    experienceId: core.serialization.string(),
    variantIndex: core.serialization.number(),
    variants: core.serialization.record(core.serialization.string(), core.serialization.string()),
});

export declare namespace HydratedExperienceFragmentViewExtensionsPersonalizationExperiencesItem {
    export interface Raw {
        experienceId: string;
        variantIndex: number;
        variants: Record<string, string>;
    }
}
