// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const HydratedViewExtensionsSourceMapNodesValueContentPropertiesItem: core.serialization.ObjectSchema<
    serializers.HydratedViewExtensionsSourceMapNodesValueContentPropertiesItem.Raw,
    ContentfulViewDelivery.HydratedViewExtensionsSourceMapNodesValueContentPropertiesItem
> = core.serialization.object({
    type: core.serialization.stringLiteral("dataAssembly"),
    dataAssembly: core.serialization.number(),
    bindings: core.serialization.record(
        core.serialization.string(),
        core.serialization.list(core.serialization.string()),
    ),
});

export declare namespace HydratedViewExtensionsSourceMapNodesValueContentPropertiesItem {
    export interface Raw {
        type: "dataAssembly";
        dataAssembly: number;
        bindings: Record<string, string[]>;
    }
}
