// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedViewExtensionsPersonalizationProfileSessionLandingPage } from "./HydratedViewExtensionsPersonalizationProfileSessionLandingPage.js";

export const HydratedViewExtensionsPersonalizationProfileSession: core.serialization.ObjectSchema<
    serializers.HydratedViewExtensionsPersonalizationProfileSession.Raw,
    ContentfulViewDelivery.HydratedViewExtensionsPersonalizationProfileSession
> = core.serialization.object({
    id: core.serialization.string().optional(),
    isReturningVisitor: core.serialization.boolean(),
    landingPage: HydratedViewExtensionsPersonalizationProfileSessionLandingPage,
    count: core.serialization.number(),
    activeSessionLength: core.serialization.number(),
    averageSessionLength: core.serialization.number(),
});

export declare namespace HydratedViewExtensionsPersonalizationProfileSession {
    export interface Raw {
        id?: string | null;
        isReturningVisitor: boolean;
        landingPage: HydratedViewExtensionsPersonalizationProfileSessionLandingPage.Raw;
        count: number;
        activeSessionLength: number;
        averageSessionLength: number;
    }
}
