// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const HydratedViewExtensionsSourceMapLayersItemSlot: core.serialization.ObjectSchema<
    serializers.HydratedViewExtensionsSourceMapLayersItemSlot.Raw,
    ContentfulViewDelivery.HydratedViewExtensionsSourceMapLayersItemSlot
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace HydratedViewExtensionsSourceMapLayersItemSlot {
    export interface Raw {
        id: string;
    }
}
