// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const HydratedExperienceFragmentViewExtensionsSourceMapAssetsItem: core.serialization.ObjectSchema<
    serializers.HydratedExperienceFragmentViewExtensionsSourceMapAssetsItem.Raw,
    ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapAssetsItem
> = core.serialization.object({
    space: core.serialization.number(),
    environment: core.serialization.number(),
    id: core.serialization.string(),
});

export declare namespace HydratedExperienceFragmentViewExtensionsSourceMapAssetsItem {
    export interface Raw {
        space: number;
        environment: number;
        id: string;
    }
}
