// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const HydratedViewExtensionsSourceMapVariantsItem: core.serialization.ObjectSchema<
    serializers.HydratedViewExtensionsSourceMapVariantsItem.Raw,
    ContentfulViewDelivery.HydratedViewExtensionsSourceMapVariantsItem
> = core.serialization.object({
    type: core.serialization.stringLiteral("personalization"),
    id: core.serialization.string(),
    experienceId: core.serialization.string().optional(),
    optimizationId: core.serialization.string().optional(),
    variantId: core.serialization.string().optional(),
    variantIndex: core.serialization.number().optional(),
});

export declare namespace HydratedViewExtensionsSourceMapVariantsItem {
    export interface Raw {
        type: "personalization";
        id: string;
        experienceId?: string | null;
        optimizationId?: string | null;
        variantId?: string | null;
        variantIndex?: number | null;
    }
}
