// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedExperienceFragmentViewExtensionsSourceMapNodesValueContentPropertiesItem } from "./HydratedExperienceFragmentViewExtensionsSourceMapNodesValueContentPropertiesItem.js";

export const HydratedExperienceFragmentViewExtensionsSourceMapNodesValue: core.serialization.ObjectSchema<
    serializers.HydratedExperienceFragmentViewExtensionsSourceMapNodesValue.Raw,
    ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsSourceMapNodesValue
> = core.serialization.object({
    layers: core.serialization.list(core.serialization.number()),
    scope: core.serialization.number(),
    contentProperties: core.serialization.list(
        HydratedExperienceFragmentViewExtensionsSourceMapNodesValueContentPropertiesItem,
    ),
});

export declare namespace HydratedExperienceFragmentViewExtensionsSourceMapNodesValue {
    export interface Raw {
        layers: number[];
        scope: number;
        contentProperties: HydratedExperienceFragmentViewExtensionsSourceMapNodesValueContentPropertiesItem.Raw[];
    }
}
