// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedExperienceViewExtensionsPersonalization } from "./HydratedExperienceViewExtensionsPersonalization.js";
import { HydratedExperienceViewExtensionsSourceMap } from "./HydratedExperienceViewExtensionsSourceMap.js";

export const HydratedExperienceViewExtensions: core.serialization.ObjectSchema<
    serializers.HydratedExperienceViewExtensions.Raw,
    ContentfulViewDelivery.HydratedExperienceViewExtensions
> = core.serialization.object({
    personalization: HydratedExperienceViewExtensionsPersonalization.optional(),
    sourceMap: HydratedExperienceViewExtensionsSourceMap.optional(),
});

export declare namespace HydratedExperienceViewExtensions {
    export interface Raw {
        personalization?: HydratedExperienceViewExtensionsPersonalization.Raw | null;
        sourceMap?: HydratedExperienceViewExtensionsSourceMap.Raw | null;
    }
}
