// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedExperienceFragmentViewExtensionsPersonalizationChangesItem } from "./HydratedExperienceFragmentViewExtensionsPersonalizationChangesItem.js";
import { HydratedExperienceFragmentViewExtensionsPersonalizationExperiencesItem } from "./HydratedExperienceFragmentViewExtensionsPersonalizationExperiencesItem.js";
import { HydratedExperienceFragmentViewExtensionsPersonalizationProfile } from "./HydratedExperienceFragmentViewExtensionsPersonalizationProfile.js";

export const HydratedExperienceFragmentViewExtensionsPersonalization: core.serialization.ObjectSchema<
    serializers.HydratedExperienceFragmentViewExtensionsPersonalization.Raw,
    ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsPersonalization
> = core.serialization.object({
    profile: HydratedExperienceFragmentViewExtensionsPersonalizationProfile,
    experiences: core.serialization.list(HydratedExperienceFragmentViewExtensionsPersonalizationExperiencesItem),
    changes: core.serialization.list(HydratedExperienceFragmentViewExtensionsPersonalizationChangesItem),
});

export declare namespace HydratedExperienceFragmentViewExtensionsPersonalization {
    export interface Raw {
        profile: HydratedExperienceFragmentViewExtensionsPersonalizationProfile.Raw;
        experiences: HydratedExperienceFragmentViewExtensionsPersonalizationExperiencesItem.Raw[];
        changes: HydratedExperienceFragmentViewExtensionsPersonalizationChangesItem.Raw[];
    }
}
