// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedFragmentViewExtensionsPersonalizationProfileLocation } from "./HydratedFragmentViewExtensionsPersonalizationProfileLocation.js";
import { HydratedFragmentViewExtensionsPersonalizationProfileSession } from "./HydratedFragmentViewExtensionsPersonalizationProfileSession.js";

export const HydratedFragmentViewExtensionsPersonalizationProfile: core.serialization.ObjectSchema<
    serializers.HydratedFragmentViewExtensionsPersonalizationProfile.Raw,
    ContentfulViewDelivery.HydratedFragmentViewExtensionsPersonalizationProfile
> = core.serialization.object({
    id: core.serialization.string(),
    stableId: core.serialization.string(),
    random: core.serialization.number(),
    audiences: core.serialization.list(core.serialization.string()),
    traits: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    location: HydratedFragmentViewExtensionsPersonalizationProfileLocation,
    session: HydratedFragmentViewExtensionsPersonalizationProfileSession,
});

export declare namespace HydratedFragmentViewExtensionsPersonalizationProfile {
    export interface Raw {
        id: string;
        stableId: string;
        random: number;
        audiences: string[];
        traits: Record<string, unknown>;
        location: HydratedFragmentViewExtensionsPersonalizationProfileLocation.Raw;
        session: HydratedFragmentViewExtensionsPersonalizationProfileSession.Raw;
    }
}
