// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const HydratedViewExtensionsSourceMapLayersItemExperience: core.serialization.ObjectSchema<
    serializers.HydratedViewExtensionsSourceMapLayersItemExperience.Raw,
    ContentfulViewDelivery.HydratedViewExtensionsSourceMapLayersItemExperience
> = core.serialization.object({
    id: core.serialization.string(),
    variants: core.serialization.list(core.serialization.number()),
    dataAssembly: core.serialization.number().optional(),
});

export declare namespace HydratedViewExtensionsSourceMapLayersItemExperience {
    export interface Raw {
        id: string;
        variants: number[];
        dataAssembly?: number | null;
    }
}
