// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedExperienceFragmentViewExtensionsPersonalizationProfileSessionLandingPage } from "./HydratedExperienceFragmentViewExtensionsPersonalizationProfileSessionLandingPage.js";

export const HydratedExperienceFragmentViewExtensionsPersonalizationProfileSession: core.serialization.ObjectSchema<
    serializers.HydratedExperienceFragmentViewExtensionsPersonalizationProfileSession.Raw,
    ContentfulViewDelivery.HydratedExperienceFragmentViewExtensionsPersonalizationProfileSession
> = core.serialization.object({
    id: core.serialization.string().optional(),
    isReturningVisitor: core.serialization.boolean(),
    landingPage: HydratedExperienceFragmentViewExtensionsPersonalizationProfileSessionLandingPage,
    count: core.serialization.number(),
    activeSessionLength: core.serialization.number(),
    averageSessionLength: core.serialization.number(),
});

export declare namespace HydratedExperienceFragmentViewExtensionsPersonalizationProfileSession {
    export interface Raw {
        id?: string | null;
        isReturningVisitor: boolean;
        landingPage: HydratedExperienceFragmentViewExtensionsPersonalizationProfileSessionLandingPage.Raw;
        count: number;
        activeSessionLength: number;
        averageSessionLength: number;
    }
}
