// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedViewExtensionsPersonalizationChangesItemExperience } from "./HydratedViewExtensionsPersonalizationChangesItemExperience.js";
import { HydratedViewExtensionsPersonalizationChangesItemFragment } from "./HydratedViewExtensionsPersonalizationChangesItemFragment.js";

export const HydratedViewExtensionsPersonalizationChangesItem: core.serialization.Schema<
    serializers.HydratedViewExtensionsPersonalizationChangesItem.Raw,
    ContentfulViewDelivery.HydratedViewExtensionsPersonalizationChangesItem
> = core.serialization
    .union("type", {
        Experience: HydratedViewExtensionsPersonalizationChangesItemExperience,
        Fragment: HydratedViewExtensionsPersonalizationChangesItemFragment,
    })
    .transform<ContentfulViewDelivery.HydratedViewExtensionsPersonalizationChangesItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace HydratedViewExtensionsPersonalizationChangesItem {
    export type Raw =
        | HydratedViewExtensionsPersonalizationChangesItem.Experience
        | HydratedViewExtensionsPersonalizationChangesItem.Fragment;

    export interface Experience extends HydratedViewExtensionsPersonalizationChangesItemExperience.Raw {
        type: "Experience";
    }

    export interface Fragment extends HydratedViewExtensionsPersonalizationChangesItemFragment.Raw {
        type: "Fragment";
    }
}
