// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedViewExtensionsPersonalization } from "./HydratedViewExtensionsPersonalization.js";
import { HydratedViewExtensionsSourceMap } from "./HydratedViewExtensionsSourceMap.js";

export const HydratedViewExtensions: core.serialization.ObjectSchema<
    serializers.HydratedViewExtensions.Raw,
    ContentfulViewDelivery.HydratedViewExtensions
> = core.serialization.object({
    personalization: HydratedViewExtensionsPersonalization.optional(),
    sourceMap: HydratedViewExtensionsSourceMap.optional(),
});

export declare namespace HydratedViewExtensions {
    export interface Raw {
        personalization?: HydratedViewExtensionsPersonalization.Raw | null;
        sourceMap?: HydratedViewExtensionsSourceMap.Raw | null;
    }
}
