// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HydratedExperienceViewExtensionsSourceMapAssetsItem } from "./HydratedExperienceViewExtensionsSourceMapAssetsItem.js";
import { HydratedExperienceViewExtensionsSourceMapDataAssembliesItem } from "./HydratedExperienceViewExtensionsSourceMapDataAssembliesItem.js";
import { HydratedExperienceViewExtensionsSourceMapEntriesItem } from "./HydratedExperienceViewExtensionsSourceMapEntriesItem.js";
import { HydratedExperienceViewExtensionsSourceMapLayersItem } from "./HydratedExperienceViewExtensionsSourceMapLayersItem.js";
import { HydratedExperienceViewExtensionsSourceMapNodesValue } from "./HydratedExperienceViewExtensionsSourceMapNodesValue.js";
import { HydratedExperienceViewExtensionsSourceMapVariantsItem } from "./HydratedExperienceViewExtensionsSourceMapVariantsItem.js";

export const HydratedExperienceViewExtensionsSourceMap: core.serialization.ObjectSchema<
    serializers.HydratedExperienceViewExtensionsSourceMap.Raw,
    ContentfulViewDelivery.HydratedExperienceViewExtensionsSourceMap
> = core.serialization.object({
    version: core.serialization.number(),
    variants: core.serialization.list(HydratedExperienceViewExtensionsSourceMapVariantsItem),
    spaces: core.serialization.list(core.serialization.string()),
    environments: core.serialization.list(core.serialization.string()),
    locales: core.serialization.list(core.serialization.string()),
    entries: core.serialization.list(HydratedExperienceViewExtensionsSourceMapEntriesItem),
    assets: core.serialization.list(HydratedExperienceViewExtensionsSourceMapAssetsItem),
    layers: core.serialization.list(HydratedExperienceViewExtensionsSourceMapLayersItem),
    dataAssemblies: core.serialization.list(HydratedExperienceViewExtensionsSourceMapDataAssembliesItem),
    nodes: core.serialization.record(core.serialization.string(), HydratedExperienceViewExtensionsSourceMapNodesValue),
});

export declare namespace HydratedExperienceViewExtensionsSourceMap {
    export interface Raw {
        version: number;
        variants: HydratedExperienceViewExtensionsSourceMapVariantsItem.Raw[];
        spaces: string[];
        environments: string[];
        locales: string[];
        entries: HydratedExperienceViewExtensionsSourceMapEntriesItem.Raw[];
        assets: HydratedExperienceViewExtensionsSourceMapAssetsItem.Raw[];
        layers: HydratedExperienceViewExtensionsSourceMapLayersItem.Raw[];
        dataAssemblies: HydratedExperienceViewExtensionsSourceMapDataAssembliesItem.Raw[];
        nodes: Record<string, HydratedExperienceViewExtensionsSourceMapNodesValue.Raw>;
    }
}
