// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const InternalServerErrorBodyI18NContextParametersValueNumber: core.serialization.ObjectSchema<
    serializers.InternalServerErrorBodyI18NContextParametersValueNumber.Raw,
    ContentfulViewDelivery.InternalServerErrorBodyI18NContextParametersValueNumber
> = core.serialization.object({
    value: core.serialization.number(),
});

export declare namespace InternalServerErrorBodyI18NContextParametersValueNumber {
    export interface Raw {
        value: number;
    }
}
