// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { InternalServerErrorBodyI18NContextParametersValueArrayNumber } from "./InternalServerErrorBodyI18NContextParametersValueArrayNumber.js";
import { InternalServerErrorBodyI18NContextParametersValueArrayString } from "./InternalServerErrorBodyI18NContextParametersValueArrayString.js";
import { InternalServerErrorBodyI18NContextParametersValueDate } from "./InternalServerErrorBodyI18NContextParametersValueDate.js";
import { InternalServerErrorBodyI18NContextParametersValueNumber } from "./InternalServerErrorBodyI18NContextParametersValueNumber.js";
import { InternalServerErrorBodyI18NContextParametersValueString } from "./InternalServerErrorBodyI18NContextParametersValueString.js";

export const InternalServerErrorBodyI18NContextParametersValue: core.serialization.Schema<
    serializers.InternalServerErrorBodyI18NContextParametersValue.Raw,
    ContentfulViewDelivery.InternalServerErrorBodyI18NContextParametersValue
> = core.serialization
    .union("type", {
        string: InternalServerErrorBodyI18NContextParametersValueString,
        number: InternalServerErrorBodyI18NContextParametersValueNumber,
        date: InternalServerErrorBodyI18NContextParametersValueDate,
        "array.string": InternalServerErrorBodyI18NContextParametersValueArrayString,
        "array.number": InternalServerErrorBodyI18NContextParametersValueArrayNumber,
    })
    .transform<ContentfulViewDelivery.InternalServerErrorBodyI18NContextParametersValue>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace InternalServerErrorBodyI18NContextParametersValue {
    export type Raw =
        | InternalServerErrorBodyI18NContextParametersValue.String
        | InternalServerErrorBodyI18NContextParametersValue.Number
        | InternalServerErrorBodyI18NContextParametersValue.Date
        | InternalServerErrorBodyI18NContextParametersValue.ArrayString
        | InternalServerErrorBodyI18NContextParametersValue.ArrayNumber;

    export interface String extends InternalServerErrorBodyI18NContextParametersValueString.Raw {
        type: "string";
    }

    export interface Number extends InternalServerErrorBodyI18NContextParametersValueNumber.Raw {
        type: "number";
    }

    export interface Date extends InternalServerErrorBodyI18NContextParametersValueDate.Raw {
        type: "date";
    }

    export interface ArrayString extends InternalServerErrorBodyI18NContextParametersValueArrayString.Raw {
        type: "array.string";
    }

    export interface ArrayNumber extends InternalServerErrorBodyI18NContextParametersValueArrayNumber.Raw {
        type: "array.number";
    }
}
