// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const LocaleStatusValue: core.serialization.Schema<
    serializers.LocaleStatusValue.Raw,
    ContentfulViewDelivery.LocaleStatusValue
> = core.serialization.enum_(["draft", "published", "changed"]);

export declare namespace LocaleStatusValue {
    export type Raw = "draft" | "published" | "changed";
}
