// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { NotFoundErrorBodyI18NContextParametersValueArrayNumber } from "./NotFoundErrorBodyI18NContextParametersValueArrayNumber.js";
import { NotFoundErrorBodyI18NContextParametersValueArrayString } from "./NotFoundErrorBodyI18NContextParametersValueArrayString.js";
import { NotFoundErrorBodyI18NContextParametersValueDate } from "./NotFoundErrorBodyI18NContextParametersValueDate.js";
import { NotFoundErrorBodyI18NContextParametersValueNumber } from "./NotFoundErrorBodyI18NContextParametersValueNumber.js";
import { NotFoundErrorBodyI18NContextParametersValueString } from "./NotFoundErrorBodyI18NContextParametersValueString.js";

export const NotFoundErrorBodyI18NContextParametersValue: core.serialization.Schema<
    serializers.NotFoundErrorBodyI18NContextParametersValue.Raw,
    ContentfulViewDelivery.NotFoundErrorBodyI18NContextParametersValue
> = core.serialization
    .union("type", {
        string: NotFoundErrorBodyI18NContextParametersValueString,
        number: NotFoundErrorBodyI18NContextParametersValueNumber,
        date: NotFoundErrorBodyI18NContextParametersValueDate,
        "array.string": NotFoundErrorBodyI18NContextParametersValueArrayString,
        "array.number": NotFoundErrorBodyI18NContextParametersValueArrayNumber,
    })
    .transform<ContentfulViewDelivery.NotFoundErrorBodyI18NContextParametersValue>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace NotFoundErrorBodyI18NContextParametersValue {
    export type Raw =
        | NotFoundErrorBodyI18NContextParametersValue.String
        | NotFoundErrorBodyI18NContextParametersValue.Number
        | NotFoundErrorBodyI18NContextParametersValue.Date
        | NotFoundErrorBodyI18NContextParametersValue.ArrayString
        | NotFoundErrorBodyI18NContextParametersValue.ArrayNumber;

    export interface String extends NotFoundErrorBodyI18NContextParametersValueString.Raw {
        type: "string";
    }

    export interface Number extends NotFoundErrorBodyI18NContextParametersValueNumber.Raw {
        type: "number";
    }

    export interface Date extends NotFoundErrorBodyI18NContextParametersValueDate.Raw {
        type: "date";
    }

    export interface ArrayString extends NotFoundErrorBodyI18NContextParametersValueArrayString.Raw {
        type: "array.string";
    }

    export interface ArrayNumber extends NotFoundErrorBodyI18NContextParametersValueArrayNumber.Raw {
        type: "array.number";
    }
}
