// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PersonalizationEventBaseContextLibrary } from "./PersonalizationEventBaseContextLibrary.js";

export const PersonalizationEventBaseContext: core.serialization.ObjectSchema<
    serializers.PersonalizationEventBaseContext.Raw,
    ContentfulViewDelivery.PersonalizationEventBaseContext
> = core.serialization
    .object({
        library: PersonalizationEventBaseContextLibrary,
    })
    .passthrough();

export declare namespace PersonalizationEventBaseContext {
    export interface Raw {
        library: PersonalizationEventBaseContextLibrary.Raw;
        [key: string]: any;
    }
}
