// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PersonalizationEventBaseChannel } from "./PersonalizationEventBaseChannel.js";
import { PersonalizationEventBaseComponentType } from "./PersonalizationEventBaseComponentType.js";
import { PersonalizationEventBaseContext } from "./PersonalizationEventBaseContext.js";
import { PersonalizationEventBaseType } from "./PersonalizationEventBaseType.js";

export const PersonalizationEventBase: core.serialization.ObjectSchema<
    serializers.PersonalizationEventBase.Raw,
    ContentfulViewDelivery.PersonalizationEventBase
> = core.serialization.object({
    channel: PersonalizationEventBaseChannel,
    context: PersonalizationEventBaseContext,
    messageId: core.serialization.string(),
    timestamp: core.serialization.string(),
    originalTimestamp: core.serialization.string().optional(),
    sentAt: core.serialization.string().optional(),
    userId: core.serialization.string().optional(),
    type: PersonalizationEventBaseType,
    name: core.serialization.string().optional(),
    event: core.serialization.string().optional(),
    properties: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    traits: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    componentId: core.serialization.string().optional(),
    componentType: PersonalizationEventBaseComponentType.optional(),
    experienceId: core.serialization.string().optional(),
    variantIndex: core.serialization.number().optional(),
    viewDurationMs: core.serialization.number().optional(),
    viewId: core.serialization.string().optional(),
});

export declare namespace PersonalizationEventBase {
    export interface Raw {
        channel: PersonalizationEventBaseChannel.Raw;
        context: PersonalizationEventBaseContext.Raw;
        messageId: string;
        timestamp: string;
        originalTimestamp?: string | null;
        sentAt?: string | null;
        userId?: string | null;
        type: PersonalizationEventBaseType.Raw;
        name?: string | null;
        event?: string | null;
        properties?: Record<string, unknown> | null;
        traits?: Record<string, unknown> | null;
        componentId?: string | null;
        componentType?: PersonalizationEventBaseComponentType.Raw | null;
        experienceId?: string | null;
        variantIndex?: number | null;
        viewDurationMs?: number | null;
        viewId?: string | null;
    }
}
