// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PersonalizationComponentEvent } from "./PersonalizationComponentEvent.js";
import { PersonalizationIdentifyEvent } from "./PersonalizationIdentifyEvent.js";
import { PersonalizationPageEvent } from "./PersonalizationPageEvent.js";
import { PersonalizationScreenEvent } from "./PersonalizationScreenEvent.js";
import { PersonalizationTrackEvent } from "./PersonalizationTrackEvent.js";

export const PersonalizationEvent: core.serialization.Schema<
    serializers.PersonalizationEvent.Raw,
    ContentfulViewDelivery.PersonalizationEvent
> = core.serialization.undiscriminatedUnion([
    PersonalizationPageEvent,
    PersonalizationTrackEvent,
    PersonalizationIdentifyEvent,
    PersonalizationScreenEvent,
    PersonalizationComponentEvent,
]);

export declare namespace PersonalizationEvent {
    export type Raw =
        | PersonalizationPageEvent.Raw
        | PersonalizationTrackEvent.Raw
        | PersonalizationIdentifyEvent.Raw
        | PersonalizationScreenEvent.Raw
        | PersonalizationComponentEvent.Raw;
}
