// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueDesignToken } from "./PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueDesignToken.js";
import { PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValue } from "./PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValue.js";

export const PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue: core.serialization.Schema<
    serializers.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue.Raw,
    ContentfulViewDelivery.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue
> = core.serialization
    .union("type", {
        DesignToken:
            PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueDesignToken,
        ManualDesignValue:
            PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValue,
    })
    .transform<ContentfulViewDelivery.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue>(
        {
            transform: (value) => value,
            untransform: (value) => value,
        },
    );

export declare namespace PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue {
    export type Raw =
        | PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue.DesignToken
        | PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValue.ManualDesignValue;

    export interface DesignToken
        extends PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueDesignToken.Raw {
        type: "DesignToken";
    }

    export interface ManualDesignValue
        extends PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValue.Raw {
        type: "ManualDesignValue";
    }
}
