// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValueValue } from "./PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValueValue.js";

export const PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValue: core.serialization.ObjectSchema<
    serializers.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValue.Raw,
    ContentfulViewDelivery.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValue
> = core.serialization.object({
    value: PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValueValue,
});

export declare namespace PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValue {
    export interface Raw {
        value: PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0ComponentTypeDesignPropertiesValueTypeValuesValueManualDesignValueValue.Raw;
    }
}
