// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueZeroDesignToken } from "./PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueZeroDesignToken.js";
import { PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueZeroManualDesignValue } from "./PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueZeroManualDesignValue.js";

export const PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueZero: core.serialization.Schema<
    serializers.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueZero.Raw,
    ContentfulViewDelivery.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueZero
> = core.serialization
    .union("type", {
        DesignToken:
            PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueZeroDesignToken,
        ManualDesignValue:
            PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueZeroManualDesignValue,
    })
    .transform<ContentfulViewDelivery.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueZero>(
        {
            transform: (value) => value,
            untransform: (value) => value,
        },
    );

export declare namespace PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueZero {
    export type Raw =
        | PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueZero.DesignToken
        | PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueZero.ManualDesignValue;

    export interface DesignToken
        extends PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueZeroDesignToken.Raw {
        type: "DesignToken";
    }

    export interface ManualDesignValue
        extends PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueZeroManualDesignValue.Raw {
        type: "ManualDesignValue";
    }
}
