// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueTypeValuesValueManualDesignValueValue } from "./PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueTypeValuesValueManualDesignValueValue.js";

export const PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueTypeValuesValueManualDesignValue: core.serialization.ObjectSchema<
    serializers.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueTypeValuesValueManualDesignValue.Raw,
    ContentfulViewDelivery.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueTypeValuesValueManualDesignValue
> = core.serialization.object({
    value: PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueTypeValuesValueManualDesignValueValue,
});

export declare namespace PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueTypeValuesValueManualDesignValue {
    export interface Raw {
        value: PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0DesignPropertiesValueTypeValuesValueManualDesignValueValue.Raw;
    }
}
