// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueTypeValuesValueDesignToken } from "./PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueTypeValuesValueDesignToken.js";
import { PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueTypeValuesValueManualDesignValue } from "./PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueTypeValuesValueManualDesignValue.js";

export const PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueTypeValuesValue: core.serialization.Schema<
    serializers.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueTypeValuesValue.Raw,
    ContentfulViewDelivery.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueTypeValuesValue
> = core.serialization
    .union("type", {
        DesignToken:
            PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueTypeValuesValueDesignToken,
        ManualDesignValue:
            PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueTypeValuesValueManualDesignValue,
    })
    .transform<ContentfulViewDelivery.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueTypeValuesValue>(
        {
            transform: (value) => value,
            untransform: (value) => value,
        },
    );

export declare namespace PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueTypeValuesValue {
    export type Raw =
        | PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueTypeValuesValue.DesignToken
        | PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueTypeValuesValue.ManualDesignValue;

    export interface DesignToken
        extends PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueTypeValuesValueDesignToken.Raw {
        type: "DesignToken";
    }

    export interface ManualDesignValue
        extends PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateDesignPropertiesValueTypeValuesValueManualDesignValue.Raw {
        type: "ManualDesignValue";
    }
}
