// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateTemplateSys } from "./PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateTemplateSys.js";

export const PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateTemplate: core.serialization.ObjectSchema<
    serializers.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateTemplate.Raw,
    ContentfulViewDelivery.PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateTemplate
> = core.serialization.object({
    sys: PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateTemplateSys,
});

export declare namespace PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateTemplate {
    export interface Raw {
        sys: PostSpacesSpaceIdEnvironmentsEnvironmentIdExperiencesId1200Schema0TemplateTemplateSys.Raw;
    }
}
