// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const RenamedHydratedTreeNode: core.serialization.Schema<
    serializers.RenamedHydratedTreeNode.Raw,
    ContentfulViewDelivery.RenamedHydratedTreeNode
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(() => serializers.RenamedComponentTreeNode),
    core.serialization.lazyObject(() => serializers.RenamedTemplateTreeNode),
]);

export declare namespace RenamedHydratedTreeNode {
    export type Raw = serializers.RenamedComponentTreeNode.Raw | serializers.RenamedTemplateTreeNode.Raw;
}
