// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EnvironmentLink } from "./EnvironmentLink.js";
import { ExperienceTemplateLink } from "./ExperienceTemplateLink.js";
import { LocaleStatusValue } from "./LocaleStatusValue.js";
import { SpaceLink } from "./SpaceLink.js";
import { UserLink } from "./UserLink.js";

export const RenamedDeliveryExperienceSys: core.serialization.ObjectSchema<
    serializers.RenamedDeliveryExperienceSys.Raw,
    ContentfulViewDelivery.RenamedDeliveryExperienceSys
> = core.serialization
    .object({
        id: core.serialization.string(),
        type: core.serialization.stringLiteral("Experience"),
        space: SpaceLink,
        environment: EnvironmentLink,
        createdAt: core.serialization.string(),
        updatedAt: core.serialization.string(),
        archivedAt: core.serialization.string().optional(),
        archivedBy: UserLink.optional(),
        archivedVersion: core.serialization.number().optional(),
        createdBy: UserLink,
        updatedBy: UserLink,
        variant: core.serialization.string().optional(),
        variantType: core.serialization.string().optional(),
        variantDimension: core.serialization.string().optional(),
        publishedAt: core.serialization.string().optional(),
        publishedVersion: core.serialization.number().optional(),
        publishedCounter: core.serialization.number().optional(),
        firstPublishedAt: core.serialization.string().optional(),
        publishedBy: UserLink.optional(),
        localeStatus: core.serialization.record(core.serialization.string(), LocaleStatusValue).optional(),
        experienceTemplate: ExperienceTemplateLink,
    })
    .passthrough();

export declare namespace RenamedDeliveryExperienceSys {
    export interface Raw {
        id: string;
        type: "Experience";
        space: SpaceLink.Raw;
        environment: EnvironmentLink.Raw;
        createdAt: string;
        updatedAt: string;
        archivedAt?: string | null;
        archivedBy?: UserLink.Raw | null;
        archivedVersion?: number | null;
        createdBy: UserLink.Raw;
        updatedBy: UserLink.Raw;
        variant?: string | null;
        variantType?: string | null;
        variantDimension?: string | null;
        publishedAt?: string | null;
        publishedVersion?: number | null;
        publishedCounter?: number | null;
        firstPublishedAt?: string | null;
        publishedBy?: UserLink.Raw | null;
        localeStatus?: Record<string, LocaleStatusValue.Raw> | null;
        experienceTemplate: ExperienceTemplateLink.Raw;
        [key: string]: any;
    }
}
