// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SpaceLinkSys: core.serialization.ObjectSchema<
    serializers.SpaceLinkSys.Raw,
    ContentfulViewDelivery.SpaceLinkSys
> = core.serialization.object({
    type: core.serialization.stringLiteral("Link"),
    linkType: core.serialization.stringLiteral("Space"),
    id: core.serialization.string(),
});

export declare namespace SpaceLinkSys {
    export interface Raw {
        type: "Link";
        linkType: "Space";
        id: string;
    }
}
