// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const UnauthorizedErrorBodySys: core.serialization.ObjectSchema<
    serializers.UnauthorizedErrorBodySys.Raw,
    ContentfulViewDelivery.UnauthorizedErrorBodySys
> = core.serialization.object({
    id: core.serialization.string(),
    type: core.serialization.stringLiteral("Error"),
});

export declare namespace UnauthorizedErrorBodySys {
    export interface Raw {
        id: string;
        type: "Error";
    }
}
