// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { UnauthorizedErrorBodyI18NContext } from "./UnauthorizedErrorBodyI18NContext.js";
import { UnauthorizedErrorBodySys } from "./UnauthorizedErrorBodySys.js";

export const UnauthorizedErrorBody: core.serialization.ObjectSchema<
    serializers.UnauthorizedErrorBody.Raw,
    ContentfulViewDelivery.UnauthorizedErrorBody
> = core.serialization.object({
    sys: UnauthorizedErrorBodySys,
    message: core.serialization.string().optional(),
    requestId: core.serialization.string().optional(),
    details: core.serialization.unknown().optional(),
    i18NContext: core.serialization.property("i18nContext", UnauthorizedErrorBodyI18NContext.optional()),
});

export declare namespace UnauthorizedErrorBody {
    export interface Raw {
        sys: UnauthorizedErrorBodySys.Raw;
        message?: string | null;
        requestId?: string | null;
        details?: unknown | null;
        i18nContext?: UnauthorizedErrorBodyI18NContext.Raw | null;
    }
}
