// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const UnprocessableEntityErrorBodyI18NContextParametersValueArrayNumber: core.serialization.ObjectSchema<
    serializers.UnprocessableEntityErrorBodyI18NContextParametersValueArrayNumber.Raw,
    ContentfulViewDelivery.UnprocessableEntityErrorBodyI18NContextParametersValueArrayNumber
> = core.serialization.object({
    value: core.serialization.list(core.serialization.number()),
});

export declare namespace UnprocessableEntityErrorBodyI18NContextParametersValueArrayNumber {
    export interface Raw {
        value: number[];
    }
}
