// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const UnprocessableEntityErrorBodySys: core.serialization.ObjectSchema<
    serializers.UnprocessableEntityErrorBodySys.Raw,
    ContentfulViewDelivery.UnprocessableEntityErrorBodySys
> = core.serialization.object({
    id: core.serialization.stringLiteral("UnprocessableEntity"),
    type: core.serialization.stringLiteral("Error"),
});

export declare namespace UnprocessableEntityErrorBodySys {
    export interface Raw {
        id: "UnprocessableEntity";
        type: "Error";
    }
}
