// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { UserOrAppDefinitionLinkType } from "./UserOrAppDefinitionLinkType.js";

export const UserLinkSys: core.serialization.ObjectSchema<
    serializers.UserLinkSys.Raw,
    ContentfulViewDelivery.UserLinkSys
> = core.serialization.object({
    type: core.serialization.stringLiteral("Link"),
    linkType: UserOrAppDefinitionLinkType,
    id: core.serialization.string(),
});

export declare namespace UserLinkSys {
    export interface Raw {
        type: "Link";
        linkType: UserOrAppDefinitionLinkType.Raw;
        id: string;
    }
}
