// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { UserLinkSys } from "./UserLinkSys.js";

export const UserLink: core.serialization.ObjectSchema<serializers.UserLink.Raw, ContentfulViewDelivery.UserLink> =
    core.serialization.object({
        sys: UserLinkSys,
    });

export declare namespace UserLink {
    export interface Raw {
        sys: UserLinkSys.Raw;
    }
}
