// This file was auto-generated by Fern from our API Definition.

import type * as ContentfulViewDelivery from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { GetWithOverridesExperienceRequestExtensions } from "../../types/GetWithOverridesExperienceRequestExtensions.js";

export const GetWithOverridesExperienceRequest: core.serialization.Schema<
    serializers.GetWithOverridesExperienceRequest.Raw,
    Omit<
        ContentfulViewDelivery.GetWithOverridesExperienceRequest,
        "preview" | "accessToken" | "optimizationProfileId" | "locale" | "variant"
    >
> = core.serialization.object({
    extensions: GetWithOverridesExperienceRequestExtensions.optional(),
});

export declare namespace GetWithOverridesExperienceRequest {
    export interface Raw {
        extensions?: GetWithOverridesExperienceRequestExtensions.Raw | null;
    }
}
