// This file was auto-generated by Fern from our API Definition.

export const ContentfulViewDeliveryEnvironment = {
    Default: "https://xdn.contentful.com",
} as const;

export type ContentfulViewDeliveryEnvironment = typeof ContentfulViewDeliveryEnvironment.Default;
